### PR TITLE
Isolate the fault tolerance support

### PR DESCRIPTION
**Pull request by rhc54**
There are at least two FT methods currently operating inside
PRRTE - the UTK method (supporting OMPI's ULFM) and the original
RCM (resilient cluster manager) method that restarts procs,
relocating them to other nodes if necessary/desirable. The latter
is only partially enabled at this time, but is scheduled for
further restoration in upcoming months. In addition, we have at
least one other organization planning to introduce its own
FT method to the code base.

In order to avoid stepping on each other, we need to cleanly
separate the implementations:

* Start at configure time by requiring specification of the
  method to be built.

* Pull the DVM errmgr code for UTK's method into its own component
  to avoid changes to PRRTE impacting their method.

* Rename the errmgr/detector component to "utk_prted" to more clearly
  indicate its function.

* Use the state machine to properly callback into that component
  instead of a PMIx event.

* Finally, restore the resilient mapper component.

These changes have been tested against the ulfm-testing harness
and verified to pass those tests when PRRTE is configured
--with-prte-ft=utk and --with-ft=ulfm provided at the mpirun
cmd line.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by abouteiller** [comment]
I don't exactly see how renaming the component 'utk' better explains its function. Our component is a failure detection and notification harness, which is it's current name. If you look at the PR https://github.com/openpmix/prrte/pull/1163 I made several weeks ago to prepare when you first talked about this work, you'll see I have left the ENABLE_FT macro free on purpose so you can reuse it. 

Having configure time selection between the methods is not acceptable. The detector should be compiled by default in future releases, this is important so that compiling a full-featured Open MPI with external PRTE (as is the case with packagers compiling for distributions) is possible. I do not see any reason why the compiled-in detector component would conflict or impede what this rcm is trying to do (It may actually help!). If there is a compatibility problem, we need to make it compatible without just disabling each other's work. 

I would argue that 'resilient' is a poor name for a feature that does automatic restart. Resilience is broader in scope than 'restart', so maybe this PR should change the component names it uses to reflect its scope.

**Comment by rhc54** [comment]
> I don't exactly see how renaming the component 'utk' better explains its function. Our component is a failure detection and notification harness, which is it's current name. If you look at the PR #1163 I made several weeks ago to prepare when you first talked about this work, you'll see I have left the ENABLE_FT macro free on purpose so you can reuse it.

I asked a while ago for suggestions on the best configure option for your FT method, but you haven't yet responded. I'm happy to make it whatever you like - 'utk' is a placeholder. Cannot use 'ulfm' or 'mpi' as those are too generic and others may have their own ideas/methods to support those areas. So please suggest what you would like in place of 'utk'.

> Having configure time selection between the methods is not acceptable.

It's a debatable point. Perhaps what we need is more flexibility in the configure option so it allows one to build multiple/all the methods if one so chooses. I'm not seeing anyone interested in reusing the pieces that are there, just as your team didn't reuse the rcm pieces that were present - it's the old story of other people wanting to do things their own way. Guaranteeing runtime separation becomes a game of whack-a-mole as people struggle with component priorities vs requiring their users to set lots of MCA params - in the end, nobody is happy.

> If there is a compatibility problem, we need to make it compatible without just disabling each other's work.

This is where I disagree - we've been that road before and it just leads to arguments and paralysis. If we can cleanly separate out the functionality, we need to do so.

> I would argue that 'resilient' is a poor name for a feature that does automatic restart. Resilience is broader in scope than 'restart', so maybe this PR should change the component names it uses to reflect its scope.

I have no issue with renaming the resilient mapper - it's a component that was in ORTE for nearly 10 years, and I simply restored it from OMPI v4. RCM was the name of the project and is how it is known - that boat left shore nearly 12 years ago. 🤷‍♂️

**Comment by jjhursey** [comment]
bot:retest:ibm

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
bot:ibm:xl:retest

**Pull request merged**
