### PR TITLE
v2.1: schizos: add --version output for ompi and prte.

### PR DESCRIPTION
**Pull request by awlauria**
For mpirun/mpiexec, grab the tool name from the environment.
This is set before the exec of prterun.

Note: this is a partial cherry-pick. Due to the differences
between master and v2.1, additional changes were needed.

Refs: https://github.com/open-mpi/ompi/pull/10120
Refs: https://github.com/open-mpi/ompi/issues/10096

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>
(cherry picked from commit 196f3246685506784de8cb52a053330e51f4a8db)

### CODE REVIEW

**Comment by gpaulsen** [comment]
bot:ibm:retest

**Review by rhc54 — CHANGES_REQUESTED** [review]
Just a general comment that would greatly simplify this change. Just initialize the tool org/msg/version strings (in prte_globals.c) to their PRRTE values. This would eleminate setting those values in all those tools. You'll just overwrite them in schizo/ompi.

Please use "PRRTE" for the tool org.

**Comment by awlauria** [comment]
bot:ibm:pgi:retest

**Review by rhc54 — APPROVED** [review]
Thanks!

**Pull request merged**
