### PR TITLE
Update handling of map/rank/bind specifications

### PR DESCRIPTION
**Pull request by rhc54**
This PR addresses the rather broad issue of clearly differentiating
between setting default values using MCA parameters versus setting
per-job parameters on the cmd line or in a comm_spawn request. Given
that PRRTE is a persistent DVM (which OMPI repurposes as a one-shot RTE
when executed as "mpirun"), it is critical that the MCA parameters only
set default policies - specifically, one cannot convert a cmd line
option into an MCA parameter for the simple reason that the MCA
parameters are only read at initial daemon startup.

In the course of making that change, a number of other issues were
uncovered and resolved:

* Fix --nolocal operation
* convert SOCKET --> PACKAGE to track changed terminology in the
  overall HPC community and within HWLOC
* Fix prte_info and mapping options such as PE-LIST and PE=N
* Correctly handle error if cannot bind to specified cpus/rank
* Remove the "map" binding output as it isn't as clear/simple
  as the string output
* Add some job-description info to the non-devel job map
  Fix backward compatibility and a bug in remote topo handling
  Get the system to work with HWLOC v1.x and PMIx v3.x by protecting the
  areas that require newer versions. Fix one place where the topology
  summary wasn't being setup if the vpid=1 daemon's topology was different
  from that of the DVM master's.
* Ensure the summaries get generated when hetero topologies are sent
  to compute node daemons.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@jsquyres I believe this is ready to test

**Comment by rhc54** [comment]
That was cute - wonder how you managed to get that to happen? Try it again

bot:ibm:xl:retest

**Comment by rhc54** [comment]
@jjhursey I cannot replicate the XL behavior anywhere else - can you please take a look? It seems to be consistent, but danged if I can see why.

**Comment by jjhursey** [comment]
The XL error is strange in two ways (1) it is only XL and (2) there are 2 nodes x 5 PPN = 10 procs, but the output shows:
```
+ prun --map-by ppr:5:node hostname
+ tee output-hn.txt
--------------------------------------------------------------------------
Your job has requested more processes than the ppr for
this topology can support:

  App: hostname
  Number of procs:  110512
  Procs mapped:  10
  Total number of procs:  110512
  PPR: 5:node

Please revise the conflict and try again.
--------------------------------------------------------------------------
```
Maybe it was transient. Let's try again just to see.
bot:ibm:xl:retest

**Comment by jjhursey** [comment]
I'm out of time for today, but I'll try to reproduce the XL compiler issue tomorrow morning (or later tonight).

**Comment by jjhursey** [comment]
I'm able to reproduce on a single node with your branch. But I'm really out of time now (kids calling from the other room) so I will need to look at it later.

**Comment by jjhursey** [comment]
@rhc54 I think I found the problem, and just pushed a fix to your branch. The `u16` needed to be initialized for the `--map-by ppr:5:node` case.

Feel free to squash that commit on your branch.

**Comment by rhc54** [comment]
Aha! Kewl - thanks!

**Pull request merged**
