### PR TITLE
Fix packing order in nidmap to match expected unpack order

### PR DESCRIPTION
**Pull request by rhc54**
Thanks to @acolinisi for the report!

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by acolinisi** [comment]
Assuming I just built the right thing, we're back to the error without :NOLOCAL:

```
prterun -n 2 hostname
batch2
--------------------------------------------------------------------------
A ppr pattern was specified, but the topology information
for the following node is missing:

  Node:  batch2
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A ppr pattern was specified, but the topology information
for the following node is missing:

  Node:  batch2
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A request has timed out and will therefore fail:

  Operation:  SPAWN: /.../openmpi-5.0.0_pre20210305/3rd-party/prrte/src/prted/pmix/pmix_server_dyn.c:631

Your job may terminate as a result of this problem. You may want to
adjust the MCA parameter pmix_server_max_wait and try again. If this
occurred during a connect/accept operation, you can adjust that time
using the pmix_base_exchange_timeout parameter.
--------------------------------------------------------------------------
```

With `-n 1` the first two errors are printed but there is no timeout, exits immediately:

```
prterun -n 1 hostname
batch2
--------------------------------------------------------------------------
A ppr pattern was specified, but the topology information
for the following node is missing:

  Node:  batch2
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A ppr pattern was specified, but the topology information
for the following node is missing:

  Node:  batch2
--------------------------------------------------------------------------
```

All good with :NOLOCAL:
```
 prterun -n 2 --map-by :NOLOCAL hostname
h22n01
h22n01

prterun -n 2 --map-by ppr:1:node:NOLOCAL hostname
h22n01
h36n14
```

**Comment by rhc54** [comment]
Is `prterun` being executed on node "batch2"?

**Comment by acolinisi** [comment]
> Is `prterun` being executed on node "batch2"?

Yes. And there are 2 compute nodes in the allocation, besides this batch2 HNP node. And there is exactly one slot on this batch2 node, and many slots on each of the compute nodes.

**Comment by rhc54** [comment]
I know what the problem is - it is in the ras/lsf component. It needs to mark that the HNP is not included in the allocation so PRRTE knows not to map any procs there. I'll try to offer a patch for you to try - might be a little bit as I have a personal obligation to meet first.

**Comment by rhc54** [comment]
Just to be clear: `batch2` isn't in the allocation reported by LSF, yes? If it is, then how are we to know that we shouldn't use it for application procs? Is there some other flag we should be looking for? Or is that (never run prterun from a compute node) a fixed feature of LSF?

**Comment by acolinisi** [comment]
Yeah, some time ago I noticed that difference between ras/lsf and ras/alps. With ras/alps, the MOM node was not included, but with ras/lsf the batch node was included. From your message sounds like ras/lsf is wrong.

I can offer you this from --mca ras_base_verbose 100:

======================   ALLOCATED NODES   ======================
        batch2: slots=1 max_slots=0 slots_inuse=0 state=UP
        flags: DAEMON_LAUNCHED:LOCATION_VERIFIED:SLOTS_GIVEN
        g07n17: slots=42 max_slots=0 slots_inuse=0 state=UP
        flags: SLOTS_GIVEN
        g07n18: slots=42 max_slots=0 slots_inuse=0 state=UP
        flags: SLOTS_GIVEN
=================================================================

If this is wrong to include batch2, then would need to look at what ras/lsf gets from LSF. I don't know how to dump the raw reply from LSF API.

**Comment by acolinisi** [comment]
FWIW, the native way is to run `jsrun`, i.e. LSF's launcher, from the batch node (batch node != login node,  to be clear). So, I assume prterun should work in the same way.

**Comment by jjhursey** [comment]
@acolinisi The `ras/lsf` component uses the blaunch API to access the host list. It basically accesses the same information that you can get from running the following in the allocation:
`cat $LSB_DJOB_HOSTFILE | sort | uniq -c`

Depending upon the exact configuration of the IBM system you are using that batch node may be included in that list (it is likely). It sounds like you are running on a CORAL-like system. For example, running the above command in a 2 node allocation on ORNL Summit yields:
```
$ cat $LSB_DJOB_HOSTFILE | sort | uniq -c
     42 a28n16
     42 a28n17
      1 batch2
```

Note that the `ras/lsf` component is doing the right thing. LSF told us that we can launch on batch2 with 1 slot. Other LSF system configurations may drop you on the first node in the allocation with more slots.

**Comment by rhc54** [comment]
Hmmm...so are we supposed to launch app procs on batch2? If not, is there a way we can/should detect that?

**Comment by rhc54** [comment]
Thinking about this a bit more, it sounds like the slot on `batch2` was allocated for use by `prterun` and not application procs. So I wonder if we should just check to see what node the ras/lsf component is on and take a slot off that node to account for `prte's` operation there? In the case @acolinisi is using, that would use all the slots on `batch2` and force all the application procs to go elsewhere - effectively the same as using `NOLOCAL`.

**Comment by jjhursey** [comment]
I don't like that as much. The CORAL LSF configuration is special in that the batch node shows up with one slot, but in other non-CORAL LSF configurations that assumption is not true. Unfortunately, LSF does not provide us with the information necessary to distinguish these two configurations. So please do not change `ras/lsf` for this special case.

On CORAL systems Spectrum MPI (based on OMPI v4.0.x with ORTE) launches like the following - which is what we expect to happen:
```
$ cat $LSB_DJOB_HOSTFILE | sort | uniq -c
     42 a28n16
     42 a28n17
      1 batch2
$ mpirun hostname | sort | uniq -c
     42 a28n16
     42 a28n17
      1 batch2
```

If they want to skip the `batch2` they can use the `:NOLOCAL`, but PRRTE should not fail out of the gate in this scenario.

**Comment by rhc54** [comment]
Perhaps we should chat on the phone as I don't see why PRRTE would fail in that scenario (it should just run hostname on the other two nodes). It sounds like you are saying you really _do_ want an application proc to run on the "batch" node? Seems odd, but I have no dog in this fight nor any understanding of what LSF is trying to do with this "batch" node.

@acolinisi Just a reminder that you could set "nolocal" as the default by appropriately putting the MCA param equivalent in your PRRTE default param file (either the system one or the one in your home directory). I believe I enabled that recently, but if not it is sitting on a branch here that I could commit shortly.

**Comment by jjhursey** [comment]
I opened Issue #804 to add support for LSF+CSM environments. Hopefully, that explains a bit more about what's going on with LSF in that configuration.

I should also note that in some CORAL configurations the node that you are placed on when you are dropped into the allocation is not the batch node, but a compute node. So identifying the batch node as the one where you launch `prterun` is not reliable in all configurations. We can continue that thread on Issue #804 if you like.

For this thread, the one thing that confused me is this part of the message:
```
prterun -n 1 hostname
batch2
--------------------------------------------------------------------------
A ppr pattern was specified, but the topology information
for the following node is missing:

  Node:  batch2
--------------------------------------------------------------------------
```
For `-n 1` there shouldn't be a ppr pattern (right?) like there would be with `-N 1` (deprecated 'npernode' alias that translates to `--map-by prr:`:node`. For example, if instead we ran `-n 2` then I would expect 1 process on `batch2` and 1 process on one of the compute nodes. Compared to `-N 2` which should fail because it is trying to put 2 process on all three nodes in the allocation, but `batch2` only has 1 slot.

**Comment by acolinisi** [comment]
> Just a reminder that you could set "nolocal" as the default by appropriately putting the MCA param equivalent in your PRRTE default param file (either the system one or the one in your home directory).

Thanks, I'll try it out, this should simplify my wrapper scripts.

**Pull request merged**
