### PR TITLE
test PMIx_Get without a fence

### PR DESCRIPTION
**Pull request by angainor**
A test that runs a single `PMIx_Get` after a `PMIx_Set` without a fence.

### CODE REVIEW

**Comment by rhc54** [comment]
@angainor Can you please sign each of these commits off: "Signed-off-by: Name \<email\>" in the commit message?

**Comment by angainor** [comment]
@rhc54 Is this what you meant?

**Comment by rhc54** [comment]
Yep, that's what we need! I already committed the "get-nofence" test, and I don't think we want the other change. The intent of "wait" is to have one proc delay its posting so the request from the other proc has to wait for it to appear. We don't want the delay to exceed the default timeout, however, or else we'd get a timeout error.

**Comment by rhc54** [comment]
So I think we can close this PR for now, unless there is something else you want changed?

**Comment by angainor** [comment]
no, thanks a lot!

**Comment by rhc54** [comment]
Thank you! Your test code was much appreciated!

**Pull request closed without merging**
