### PR TITLE
First cut of Sphinx / ReadTheDocs docs

### PR DESCRIPTION
**Pull request by jsquyres**
Took all content from README, README-Resilience, INSTALL, and HACKING and put them in various files in the docs/ subdirectory.  Made empty man pages for all the PRRTE executables that are installed.

Also copied a bunch of stock material from the Open MPI Sphinx docs (e.g., several pages from
https://github.com/open-mpi/ompi/tree/main/docs/developers).

Much editing still needs to be done; this commit is mainly about the configure/build infrastructure (e.g., setting up Sphinx and getting "make dist" to work properly).  The RST documentation content that is provided is still incomplete.

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by rhc54** [comment]
Just thinking - we actually have "man page" similar text for the PRRTE executables. If there is an easy way to transfer ".txt" files to ".rst", that should be easy to do. Clearly works for `prte_info` and `prted`.

Problem is that the actual man page for the other executables depends upon the personality being invoked. So the man page for `prterun`, for example, is different when invoked with the default `prte` personality then when invoked with the `ompi` one.

I first thought one could just generate separate man pages based on the proxy name - `prterun` vs `mpirun` - but that won't work either because MPICH also uses that proxy name, and someone could pass `--personality ompi` to the `prterun` cmd and get the OMPI `mpirun` cmd line.

How might we handle that here?

**Comment by jsquyres** [comment]
Converting .txt --> .rst: not to difficult to do.  It's manual, but it's pretty much a one-time cost.  Point me at the .txt files.

Personality-based man pages: we obviously can't pass a `--personality` CLI-like flag to `man`.  The corresponding `.rst` files have to be fixed text.  If there are known set of personalities, you could make pages like `mpirun.openmpi.1.rst` and `mpirun.mpich.1.rst`, for example.

It might be sufficient to have a top-level `prterun.1.rst` file that has all the stuff that's the same between all the personalities, and then have "See also" references for `mpirun.openmpi.1.rst` and `mpirun.mpich.1.rst`, and then those 2 pages just document the differences from `prterun(1)`.  Would something like that work for you?

**Comment by jsquyres** [comment]
Of course, you could also have just one large `prterun.1.rst` and have sections in it for the different personalities, too.  That's also definitely an option.  I don't think there's any "right" or wrong way to do it.

**Comment by rhc54** [comment]
I think having something at the top of the `prterun` page that explains the personality thing with links that point to where you can find the actual page for your personality is probably the way to go. The default `prte` personality can be on the rest of that page.

**Comment by naughtont3** [comment]
Just noticed this ticket - I wonder if the "personality" aspect could be in the SEE ALSO set of manpages, so folks would know to look for the `prterun_mpich.1` and `prterun_ompi.1` by looking at the top-level `prterun.1`?

**Comment by jsquyres** [comment]
> Just noticed this ticket - I wonder if the "personality" aspect could be in the SEE ALSO set of manpages, so folks would know to look for the `prterun_mpich.1` and `prterun_ompi.1` by looking at the top-level `prterun.1`?

FWIW: This is no longer a technical issue, but rather a "it's however you guys want to write the content" kind of issue. 😄 

This PR is a starter for the PRTE community -- I probably won't write much more content beyond this PR.

FWIW: This PR (and the corresponding PMIx PR) are waiting on a fix in the OAC repo.  Once that gets in, these two PRs will be updated to point to the latest OAC and then they'll be good to go.

**Comment by jsquyres** [comment]
I should clarify my above comments...

PRRTE should feel free to liberally steal `prterun.1.rst` content from https://github.com/open-mpi/ompi/blob/main/docs/man-openmpi/man1/mpirun.1.rst.  I don't expect that all of that content is entirely correct with respect to PRTE's current `prterun` behavior, but it could save a bunch of initial work / be a good starting point.  If this effectively means that much of Open MPI's current `mpirun.1` content moves to `prterun.1`, then perhaps Open MPI's `mpirun.1` should become much shorter -- maybe something like:

* Describe `mpirun`'s relationship to `prterrun`
* Describe any `mpirun`-specific behavior
* Include a pointer to `prterun(1)`

I have thought about schemes to include `prterun.1.rst` inside `mpirun.1.rst` so that the user has a simple/seamless experience (i.e., `man mpirun` shows them all relevant information, as opposed to also needing to run/read `man prterun`), but that seems sketchy for at least the following reasons:

* If Open MPI is used with its embedded PRTE, we might be able to pull that off.
* But if Open MPI is used with an external PRTE, how would Open MPI's build system know where to find `prterun.1.rst` to include in its `mpirun.1.rst`?  This is especially complicated because the choice of *which* external PRTE to use could be made at run time (vs. Open MPI's build time).
* Recall that Open MPI distribution tarballs ship with pre-built HTML/nroff Sphinx docs.  Realistically, then, the pre-built `mpirun.1` HTML and nroff content can only contain the `prterun.1.rst` content from the embedded PRTE (because that's all that's available when the distribution tarball is built).  But this could be problematic if a user utilizes an external PRTE: `man mpirun` could contain wrong information if distribution tarball embedded PRTE `prterun.1.rst` content is different that the external PRTE's `prterun.1.rst`.

This all seems like a can of worms that is not worth opening.  Hence -- assuming PRTE's `prterun.1.rst` gets fleshed out into full docs -- a short Open MPI `mpirun.1.rst` (as described above) might be the best solution.

**Comment by jsquyres** [comment]
@rhc54 https://github.com/open-mpi/oac/pull/7 has merged; this PR is now ready for review.

However, per https://github.com/openpmix/openpmix/pull/2858#issuecomment-1372660400 and https://github.com/openpmix/openpmix/pull/2858#issuecomment-1372682783, we'll likely have `make dist` CI failures here, too.

**Comment by jsquyres** [comment]
Huzzah!  It wasn't hard to update the MLNX Github action to install Sphinx, and therefore to enable `make dist` to succeed.

**Pull request merged**
