### PR TITLE
build: Remove unnecessary configure tests

### PR DESCRIPTION
**Pull request by bwbarrett**
Many of the configure tests that PRRTE runs are either not used
(ie, checking for a case sensitive file system or 128 bit integers)
or we use the tested item without conditionals throughout the code
(ie, we use stdbool.h in multiple places and none of them have
conditional checks).  The second really isn't an issue; of the
places I found that behaivor, we're likely leaving behind some
ancient systems, but that hasn't proven to be a problem at this
point.

This patch removes all the tests where we didn't use the results.
There is likely more shortening of the configure script that
we could do, but this was the low hanging fruit.

Signed-off-by: Brian Barrett <bbarrett@amazon.com>

### CODE REVIEW

**Comment by bwbarrett** [comment]
@rhc54 I'm totally fine if you don't want to take this.  It was an experiment based on your comments about configure runtime in containers during last night's IU basketball game.  The code should work, it does make configure faster, but it's also code changes, so it might just muck things up.

**Comment by rhc54** [comment]
I suspect a lot of these went away when we shifted utilities and other shared infrastructure over to PMIx. I see no problem with doing it - if we miss some system, they'll let us know 😄

**Comment by rhc54** [comment]
Sorry - I've tried redelivering the signed-off-by payload multiple times with no success. No idea what the problem is - probably best to just push something into it?

**Comment by bwbarrett** [comment]
GitHub Actions are experiencing problems according to https://www.githubstatus.com/.  I think the right answer is to wait until GitHub is healthy again.

**Pull request merged**
