### PR TITLE
initialize installdirs variable for prte_info tool

### PR DESCRIPTION
**Pull request by naughtont3**
Signed-off-by: Thomas Naughton <naughtont@ornl.gov>

### CODE REVIEW

**Comment by naughtont3** [comment]
fixes #290

**Comment by rhc54** [comment]
Ah - I didn't realize you were running that tool when you encountered the segfault! Now I understand why you were seeing something different from Jeff and I. Thx!

**Comment by naughtont3** [comment]
Actually, I see another issue related to a hang that's different from what you and Jeff saw.  But I'm not able to isolate the difference for why I'm the only one seeing the hang.  It is sitting in `opal_progress()` on both sides of a 2 rank ring test after passing message around ring 2 times.  But that's all different from this issue.

**Comment by rhc54** [comment]
These are known errors - we have something hanging at end of job.

**Comment by naughtont3** [comment]
> These are known errors - we have something hanging at end of job.

Ah!  OK

**Pull request merged**
