### PR TITLE
Carry across the PRRTE toolname to PMIx

### PR DESCRIPTION
**Pull request by rhc54**
Ensure PMIx knows the upper-level toolname

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@awlauria I just separated this out of a much larger branch - no need to tie things up for that work to complete.

**Review by awlauria — APPROVED** [review]

**Comment by awlauria** [comment]
I think this is missing the `extern char *pmix_tool_basename` at the top of this file.

**Comment by rhc54** [comment]
Bah - had a related change for PMIx. Will bring that one over first.

**Comment by rhc54** [comment]
bot:ibm:retest

**Pull request merged**
