### PR TITLE
ensure search_dirs populated with datadir for help

### PR DESCRIPTION
**Pull request by naughtont3**
Signed-off-by: Thomas Naughton <naughtont@ornl.gov>

### CODE REVIEW

**Comment by naughtont3** [comment]
I kind of doubt this is right way to solve this but adding to clarify the problem I was seeing when testing with `v2.1` branch.  The show help, even for recognized and well-formed options (e.g., `prterun --help`) were silently returning w/ non-zero retval (`PRTE_ERR_SILENT`).  The `search_dirs[]` were empty, so no helpfiles were located and things just silently bail out b/c there's no info to share.

**Comment by naughtont3** [comment]
Example output for notes:
```
node0: (v2.1)$ git br
  showhelp-tweak
* v2.1
node0: (v2.1)$ prterun -h
node0: (v2.1)$ prterun --help
node0: (v2.1)$ prterun --version
node0: (v2.1)$ echo $?
213
node0: (v2.1)$ prterun --help
node0: (v2.1)$ echo $?
213
node0: (v2.1)$ prterun -h
node0: (v2.1)$ echo $?
213
node0: (v2.1)$
```

```
node0: (showhelp-tweak)$ git br
* showhelp-tweak
  v2.1
node0: (showhelp-tweak)$ 
node0: (showhelp-tweak)$ prterun --version 
prterun (PRRTE) 2.1.0a1

https://github.com/openpmix/prrte/
node0: (showhelp-tweak)$ prterun -h | head
prterun (PRRTE) 2.1.0a1

Usage: prterun [OPTION]...
Initiate an instance of the PMIx Reference RTE (PRRTE) DVM

/*****      General Options      *****/

-h|--help                            This help message
-h|--help <arg0>                     Help for the specified option
-v|--verbose                         Enable typical debug options
node0: (showhelp-tweak)$ prterun --help | head
prterun (PRRTE) 2.1.0a1

Usage: prterun [OPTION]...
Initiate an instance of the PMIx Reference RTE (PRRTE) DVM

/*****      General Options      *****/

-h|--help                            This help message
-h|--help <arg0>                     Help for the specified option
-v|--verbose                         Enable typical debug options
```

Note still have non-zero retval for `--help` but maybe I just did not notice in past.

```
node0: (showhelp-tweak)$ prterun --help > /dev/null
node0: (showhelp-tweak)$ echo $?
213
node0: (showhelp-tweak)$
```

**Comment by naughtont3** [comment]
might related to #1360

**Comment by rhc54** [comment]
Fixed by updating of PRRTE v2.1 branch

**Pull request closed without merging**
