### PR TITLE
Let PMIx compute locality string for v4

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
PRRTE CI seems to be failing in launch with the following on the remote daemons:
`[prted.c:683] PMIx Error: NOT-SUPPORTED`

**Comment by rhc54** [comment]
Yes - I'm working on it 😄

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
Travis hung again after succeeding.

**Pull request merged**
