### PR TITLE
Initiate move of CLI help files to common location

### PR DESCRIPTION
**Pull request by rhc54**
In order to make it easier for 3rd-parties to automate the assembly of their own help docs, move the CLI help files to a new common location. Retain their names so we don't have to go back and update everywhere they are used, and ensure they still get installed to the proper location that show_help is expecting.

### CODE REVIEW

**Comment by rhc54** [comment]
@jsquyres This PR moves two CLI help files into a new common location at `src/docs`. I also realized that I have done very little with the PRRTE documentation beyond the CLI help text, focusing my time more on the PMIx side of things. I'll hold off doing anything on it until we know the final results of our chat.

**Comment by jsquyres** [comment]
Rebased to fix conflicts.

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Comment by jsquyres** [comment]
Status report: much has been done, but there's still more to do.

3 `.txt` files were 1:1 converted to `.rst` files.  First cut of Sphinx plugin is written that renders new, custom RST directives in the `.rst` files to HTML+nroff and txt (i.e., INI-style show_help file) -- it all mostly works (see below for one case that isn't quite right yet).  Configury and sym links are in place to make this all work, `make distcheck` works, and the rendered output is all (mostly) as expected.

- [ ] Fix Sphinx prterun-section plugin glitch that does not return to the proper doc level when exiting a section with subsections
- [ ] Re-order content in the newly-created RST files so that when rendered to HTML/nroff, they tell a cohesive story
- [ ] Finish corresponding Open MPI side of things:
    - [ ] Slurp in PRTE RST files to make cohesive mpirun.1 RST
    - [ ] Make cohesive header / footer / other sections in mpirun.1 RST to tell a complete mpirun man page story
    - [ ] Add sym links / configury / whatever to find these RST files for the embedded PRTE
    - [ ] For external PRTE:
        - [ ] First cut: make the rendered mpirun.1 RST files say "You built with an external PRTE. The information here may be different yadda yadda yadda", and then slurp in the RST files for the embedded PRTE
        - [ ] Extra bonus points: slurp in the installed PRTE RST files (instead of the RST files for the embedded PRTE)
    - [ ] Ensure that distcheck passes, and that the rendered HTML+man pages for mpirun are correct

I'm probably the one that needs to fix the Sphinx plugin, but assistance on the other steps would be great.

**Comment by jsquyres** [comment]
@rhc54 I don't think this is done yet, and I'm sure there are still content / flow errors.  But it contains most of what we talked about today.  What do you think?  In particular, look at these 4 files:

* `docs/man/man1/prterun.1.rst`
* `src/docs/help-schizo-cli.rst`
* `src/docs/help-schizo-deprecated.rst`
* `src/docs/help-schizo-placement.rst`
    * I renamed this from `help-schizo-detail.rst`, which may not have been a good idea (is there code that refers to `help-schizo-detail.txt`?)

**Comment by rhc54** [comment]
> I renamed this from help-schizo-detail.rst, which may not have been a good idea (is there code that refers to help-schizo-detail.txt?)

My original plan was to collect all the sections that are strictly indirectly referenced in that file - hence the generic name. However, that plan no longer fits what we discussed, so renaming it is fine. Would have to rename some places that refer to the "detail" name, but I'm going to have to do that regardless, I think - not clear to me that we will wind up replicating names across the board. Thankfully, it can be done with a global search/replace.

> What do you think?

Pretty much looks like what we described. The `placement-deprecated` section is what you would now call the `deprecated-map-by`, which seems to have been split into a variety of deprecated files, each for one deprecated CLI option?

I guess it follows the pattern of what you did for each CLI option. I can grok the idea - make it so atomistic that someone can pick/choose the individual options they want to use. I just hadn't taken what we discussed and gone to that level of atomicity. No real objection to it - just a tad more than I was expecting.

Given that, I'm not sure I understand the need for `src/docs/help-schizo-cli.rst`. The output from that file (and the others like it that you cite) don't seem to "fit" any more. Instead, I would need to create a `src/mca/schizo/prte/help-schizo-prterun.rst` file that has the overview in it and then all the "include" directives for the individual options. This would then generate the corresponding text file used by show-help. No reason for me to include directives that reference a file that contains all the generic entries - just duplicate work (create the generic file and then create a top-level file that references them).

Is that correct? Or am I missing something?

**Comment by rhc54** [comment]
Couple of thoughts. I realized that the reason for your current files was to minimize the near-term conversion impact on me. However, I think it creates a long-term coherence issue. If we are going to convert the show-help CLI system over to RST, then we probably should bite the bullet and do it. If all I have to do is convert the top-level CLI help text files in the schizo/prte component, that isn't such a big deal. Would be much worse if we were converting all the show-help error output - maybe someone can someday do it, but we should avoid that for now.

My other thought is for extensibility. Today we limit the help CLI system to the option, but no suboption - i.e., you can do `prterun --help display` but you cannot do `prterun --help display alloc`. This is a limitation I would like to remove fairly soon. We'd like to be able to do something like provide more detail on that specific suboption, perhaps including example output.

I don't believe your proposed system would preclude this. We might do something like add a `display-alloc` entry somewhere and update the `show-help` function to concatenate the option and suboption to create the lookup tag. Since the goal would be to provide more detail than just `--help display` would produce, I wouldn't expect `--help display` to include a link to the `display-alloc` entry. I suppose there would be no harm in including the `display alloc` detail on the web site if it was desirable.

Just raising it here in case you see something that would preclude that extension.

**Comment by jsquyres** [comment]
@rhc54 Per our Slack conversation, I agree with everything you mentioned above.

I converted the rest of the `help-<cmd>` show help files, and put them in `src/docs`.  I then converted all their `#include` directives to be RST `.. include::` directives.  I think it's all working -- can you give it a look?

Also, I was having difficulty in getting all the individual files from `src/docs/SINGLE_TOPIC.rst` included properly in `docs/man/man1/COMMAND.rst` (because of the `SINGLE_TOPIC.rst` files include other `SINGLE_TOPIC.rst` files, and the include paths are different.  I finally gave up and sym linked all the `SINGLE_TOPIC.rst` files into `docs/man/man1/prterun`, just in an effort to get this done/working (on the assumption that I could do something cleaner later).

But then I had a thought: why not make the `docs/man/man1/COMMAND.rst` files be very bare-bones, saying essentially "You should look at COMMAND --help for all the help about this command."

What do you think of that idea?

If you're ok with all of this, I think this side of the work is getting close to done.  I need to refresh https://github.com/open-mpi/ompi/pull/11820 (because things changed here a bit), but we might be getting close...?

**Comment by jsquyres** [comment]
> What do you think of that idea?

Turns out that this isn't the greatest idea, because all the same problems with including content in PRTE man pages come up in pretty much the same way when trying to include content in OMPI man pages.

Meaning: it's worth solving those issues here in PRTE, and then replicating that solution in OMPI.  Working on it...

**Comment by jsquyres** [comment]
After talking with @rhc, we agreed to merge and fix up any translation / content errors once it's in.

**Pull request merged**
