### PR TITLE
Begin conversion to use of nspace

### PR DESCRIPTION
**Pull request by rhc54**
Eventually, we want to replace the integer jobid with the PMIx nspace.
This is necessary for dealing with 3rd-party tools that will present us
with arbitrary namespaces, which we are already beginning to encounter.
This begins the process by maintaining both the original uint32_t jobid
and the corresponding nspace.

Fixes a problem with proxy launches as the `prun` tool would have its assigned name changed when it connected to the spawned `prte` DVM, thus causing confusion in the rest of PRRTE.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@jjhursey I'm not entirely sure I agree with this proxy test you are running as it isn't clear to me that we should recognize "myrun" as a supported proxy. I can see "mpirun" and "mpiexec" meaning something - but are we truly going to support totally arbitrary commands? What programming personality am I supposed to associate with "myrun"?

Maybe it would be better if you used the `PRRTE_MCA_schizo_base_test_proxy_launch=1` param that was specifically defined for testing this feature.

**Comment by jjhursey** [comment]
I was trying to emulate the mpirun setup. We can change the test. Would it be better if it was named `mpirun` instead of `myrun`?

**Comment by rhc54** [comment]
Just set the MCA param - it does the same thing and avoids any confusion over another `mpirun` in the system.

**Comment by jjhursey** [comment]
PR https://github.com/openpmix/pmix-tests/pull/57 should fix the test. We can retest once it goes in.

**Comment by rhc54** [comment]
bot:ibm:retest

**Pull request merged**
