### PR TITLE
Fix bug in not updated cached daemon topologies

### PR DESCRIPTION
**Pull request by wckzhang**
Cached daemons weren't properly having their topologies updated.
If the topology sig matches, sets the cached daemon topology to
the current topology.

Signed-off-by: William Zhang <wilzhang@amazon.com>

### CODE REVIEW

**Comment by wckzhang** [comment]
Fixes #10641

**Comment by rhc54** [comment]
Yeah, I was just responding to your note on the issue. I'll bring it over there.

I agree that you have identified the bug, but this fix doesn't look complete somehow. I don't see "t" being assigned above that point. You would need it to point to the node->topology of the rank=1 daemon, but that isn't getting set until later. So I think you are "getting lucky" with this change and it will likely segfault elsewhere.

Correctly getting the node topology set is going to be a little tricky and likely require additional changes below. Let me start with this and update your PR with a more complete fix.

**Comment by wckzhang** [comment]
Huh weird, I thought t was being set. I'm surprised it didn't segfault

**Comment by wckzhang** [comment]
Maybe we can delay the progressing of cached daemons until later...I'll post an update

**Comment by rhc54** [comment]
No, that's okay - I have it fixed here. Just getting ready to push.

**Comment by rhc54** [comment]
Okay, I updated your branch

**Comment by rhc54** [comment]
Please see if it still solves your problem.

**Comment by wckzhang** [comment]
Oh I get a segmentation fault

**Comment by rhc54** [comment]
Can you post something about it?

**Comment by wckzhang** [comment]
Yeah I'm currently debugging it give me a second

**Comment by rhc54** [comment]
No worries - feel free to fix it as you see fit. If you prefer to try and delay the cached daemon processing, I have no issue with doing so. I'm just not sure that is going to be much easier, but I haven't looked at it.

**Comment by wckzhang** [comment]
I have a patch for the delayed cached daemon processing which doesn't segfault, let me update the PR

**Comment by wckzhang** [comment]
Updated

**Comment by rhc54** [comment]
Looks reasonable to me - thx!

**Comment by wckzhang** [comment]
@rhc54 can you merge? I don't have merge permissions on this repo

**Pull request merged**
