### PR TITLE
Convert man pages to Markdown + other general cleanups

### PR DESCRIPTION
**Pull request by jsquyres**
Inspired by https://github.com/jsquyres/pmix-master/pull/new/pr/pandoc-generated-man-pages, use Pandoc to generate nroff man pages, instead of maintaining nroff files manually.

Also included a handful of other minor cleanups in separate commits; see individual commit messages for details.

### CODE REVIEW

**Comment by jsquyres** [comment]
@jjhursey Are you using `pcc` to compile things in your CI jobs?  I removed it in this PR because it seemed redundant with `pmixcc`...  Should I put it back?

**Comment by rhc54** [comment]
Yeah, I forgot about that - we should probably put it back. Intel is also using `pcc` in their tests because people don't always have PMIx install its tools. It will become more common as the tool catalog expands (we now have three and will soon add a fourth), but for now we probably do need PRRTE to emit a wrapper compiler too.

We can review the name later - would have to coordinate that with the current folks who use `pcc`.

**Comment by jsquyres** [comment]
> Yeah, I forgot about that - we should probably put it back. Intel is also using `pcc` in their tests because people don't always have PMIx install its tools. It will become more common as the tool catalog expands (we now have three and will soon add a fourth), but for now we probably do need PRRTE to emit a wrapper compiler too.

I hear what you're saying, and I'll put pcc back on this PR, but it *is* weird to emit a wrapper compiler for a project that has no public interface libraries.  I.e., it's basically a stand-in for the PMIx wrapper compiler if you didn't install the PMIx wrapper compiler.  My point: if you're going to compile PMIx applications, you need `pmix.h` and therefore you should use the real `pmixcc`.   ...right?

**Comment by rhc54** [comment]
> I hear what you're saying, and I'll put pcc back on this PR, but it _is_ weird to emit a wrapper compiler for a project that has no public interface libraries. I.e., it's basically a stand-in for the PMIx wrapper compiler if you didn't install the PMIx wrapper compiler. My point: if you're going to compile PMIx applications, you need `pmix.h` and therefore you should use the real `pmixcc`. ...right?

Not really. Remember, PRRTE had to be built against some version of PMIx - so all this wrapper compiler does is help you build against the _same_ version of PMIx used by PRRTE. It's true that the app won't be calling `prrte_init` and doesn't actually link against `libprrte` (it links instead against `libpmix`), but it does ensure that you are using a compatible PMIx library. So one could argue this either way.

Regardless, that is why we added it - so that people could build their PMIx-dependent apps against a PMIx that PRRTE was guaranteed to support.

**Pull request merged**
