### PR TITLE
support for cmdline "--mca prrte_tools_entry lib"

### PR DESCRIPTION
**Pull request by markalle**
Another schizo directory registers a couple --mca variables
and uses them to modify LD_LIBRARY_PATH and possibly LD_PRELOAD.

This supports a larger checkin in OMPI where a new library
intercepts all the MPI calls and allows dynamic layering of
PMPI wrappers.

### CODE REVIEW

**Comment by markalle** [comment]
This goes with OMPI PR
https://github.com/open-mpi/ompi/pull/6245

**Comment by markalle** [comment]
I repushed with a model that I think is more consistent with the notion of persistent prrte vs per-job settings.  The -entry command line ends up visible in the char **dstenv list that includes OMPI_MCA_ompi_* settings.  From there an extra script is prepended in the app's argv list to ensure the OMPI rank sees the LD_LIBRARY_PATH it wants.

**Comment by jjhursey** [comment]
Any update on this PR?

**Comment by rhc54** [comment]
This is very old/stale - please rebase, update, and reopen if anyone still cares.

**Pull request closed without merging**
