### PR TITLE
Rename the "rsh" PLM to "ssh"

### PR DESCRIPTION
**Pull request by jsquyres**
It's probably about time to have an "ssh" PLM that also just happens to support "rsh" (vs. an "rsh" PLM that also just happens to support "ssh").

Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by jsquyres** [comment]
I figured I'd submit this PR near the beginning of PRRTE's life so that there's a chance we won't get saddled with the legacy "rsh" name forever.  😄

**Comment by rhc54** [comment]
I have no objections to doing this, but don't we need synonyms for the various params so we don't break scripts based on prior versions of OMPI? I know we did something to allow component synonyms in OMPI (e.g., vader and shmem) - we might need to bring that across as people will have set `--mca plm rsh` in their scripts/environment. Would that be hard to do?

**Comment by jsquyres** [comment]
Yes, probably so.  Did PRRTE copy OMPI's concept of synonyms?

**Comment by rhc54** [comment]
I think that came after we "fork'd", and I don't recall bringing it across. Is there an easy way to tell?

**Comment by jsquyres** [comment]
Wait for #731 to merge, and then put in an alias for the `ssh` component to also be known as the `rsh` component.

**Comment by rhc54** [comment]
Replaced by #780

**Pull request closed without merging**
