### PR TITLE
Silence Coverity warnings and enable prun to forward signals

### LINKED ISSUE #451: prun needs to catch and forward signals
Restore the signal forwarding capabilities of mpirun, including allowing the user to specify which signals are to be forwarded

### PR DESCRIPTION
**Pull request by rhc54**
Silence a slew of Coverity warnings 

 Enable prun to catch/forward user-specified signals 

Fixes #451 

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
CI is stumbling on a warning message from the signal portion of this PR:
> [warn] Added a signal to event base 0x10002872370 with signals already added to event_base 0x10002837a70.  Only one can have signals at a time with the epoll backend.  The base with the most recently added signal or the most recent event_base_loop() call gets preference; do not rely on this behavior in future Libevent versions.

**Comment by rhc54** [comment]
@jjhursey is this with your proxy-run setup? I'm not seeing it otherwise

**Comment by jjhursey** [comment]
They are all failing in the hello_world test - no wrapper.

```
+ prte --daemonize --hostfile /workspace/hostfile.txt
+ date
Tue Mar 17 19:05:14 UTC 2020
+ sleep 5
+ date
Tue Mar 17 19:05:19 UTC 2020
+ prun --map-by ppr:5:node hostname
+ tee output-hn.txt
[warn] Added a signal to event base 0x10002872370 with signals already added to event_base 0x10002837a70.  Only one can have signals at a time with the epoll backend.  The base with the most recently added signal or the most recent event_base_loop() call gets preference; do not rely on this behavior in future Libevent versions.
81ff9382f281
81ff9382f281
...

```

**Comment by rhc54** [comment]
Just taking a shot in the dark here - I cannot replicate, so let's see if this works

**Pull request merged**
