### PR TITLE
Make allgather signature consistent for server_connect_fn()

### PR DESCRIPTION
**Pull request by wzamazon**
pmix_server_connect_fn() call grpcomm.allgather(), which
uses a signature to identify the action.

pmix_server_connect_fn() uses "procs" (which is an array
of pmix_proc_t) as signature.

procs was provided by client when it called PMIx_connect().

The issue is that different client may have procs in different
order (when inter MPI communicator trascation is used).
As a result, pmix servers may end up with different signature
for the same allgather operation.

This patch addressed the issue by sorting "procs" by
pmix_proc_t before passing it to grpcomm.allgather.

Signed-off-by: Wei Zhang <wzam@amazon.com>

### CODE REVIEW

**Comment by rhc54** [comment]
Hmmm... this is a bit of a problem. PMIx states that the proc array is order sensitive, which is why we treat it that way here. This breaks that correlation. Might solve OMPI's issue but create problems for apps and libraries that follow the standard.

Perhaps a better solution would be to do the sort in OMPI prior to calling connect?

**Comment by wzamazon** [comment]
> PMIx states that the proc array is order sensitive, 

Thank you!

Can you point me to the document? I tried to find document regarding procs ordering, but could not find it.

> Perhaps a better solution would be to do the sort in OMPI prior to calling connect?

Yes. I can definitely modify OMPI too.

**Comment by rhc54** [comment]
I'm on the road today but will post the link later. For now please modify the OMPI side

**Comment by wzamazon** [comment]
> For now please modify the OMPI side

will do. Thank you!

**Pull request closed without merging**
