### PR TITLE
Failure detection and propagation in PRRTE

### PR DESCRIPTION
**Pull request by dong0321**
We present here the design and implementation of our runtime-level failure detection and propagation strategy targeting large-scale, dynamic systems that is able to detect both node and process failures.

Multiple overlapping topologies are used to optimize the detection and propagation, minimizing the incurred overheads and guaranteeing the scalability of the entire framework.

### CODE REVIEW

**Comment by rhc54** [comment]
@dong0321 Some of the commits appear to be missing the required sign-off - could you please add it?

I'd like to get this into the code base, but I only had time to do a quick scan for now and noted a couple of things:

* we would need this feature to be "off" by default, not "on", until people have a chance to work with it a bit. It's coming in right on the edge of the deadline, and so we won't have much time to test it out

* I don't think the new grpcomm component is quite right. The problem is that the OOB will only create connections based on the routed component's "hops", yet the bmg component appears to be ignoring that pattern and addressing its messages to a different set of targets. This means that each message is getting bounced around the routed "hops" as it tries to reach its destination. I think what you really wanted was to create a different routed component that matches your desired pattern, and then have bmg send to the "leaves" of that pattern?

If you can modify the code to turn things "off" by default, we can resolve the other things over time.

**Comment by dong0321** [comment]
@rhc54 Thank you for the comments. 
(1) I rebased, squashed  and signed-off all my commits, it should be better now.
(2) I made some changes to set this feature to be "off" by default, the user can use it by passing mca params. 
(3) We noticed this problem.  At this point  we assume users will pass correct params for routed which can ensure direct rerouted. I think we can discuss and update this later.

**Comment by rhc54** [comment]
Rats - we are hitting conflicts due to some renaming Jeff did.

@dong0321 My apologies - can you please resolve the conflicts so we can commit?

**Comment by dong0321** [comment]
Thanks, I will get it done.

**Comment by jjhursey** [comment]
Per teleconf on June 4, 2020 we decided to bring this in now.
Thank you for all the hard work on this enhancement!

**Comment by jjhursey** [comment]
ok to test

**Comment by jjhursey** [comment]
@dong0321 Just before I was going to hit the merge button I noticed that CI didn't run on these builds so I kicked it off. It worked fine in the DVM mode, but failed in the wrapper mode (mpirun-like). Can you take a look?

The test is here:
 * https://github.com/openpmix/pmix-tests/blob/master/prrte/prun-wrapper/run.sh

**Comment by rhc54** [comment]
There were a lot of warnings and a few compile errors in here that I have fixed to the best of my understanding. In two places, there was an ambiguous "if" clause - I tried to guess how many lines under the "if" were supposed to be covered by each clause, but no way of telling if I got it right.

@dong0321 You should double-check this after it gets committed. It would also be nice if someone could do a general cleanup to match the coding style of the project and make things a little clearer.

**Comment by dong0321** [comment]
I will check and solve the warnings this weekend, and match the code style.

**Comment by rhc54** [comment]
@dong0321 Just to clarify - I already fixed the warnings, though I think you should check that what I did is correct. I'm going to go ahead and commit this just to ensure that we don't get caught by another conflict. We can address the remaining issues in a separate PR when you have time.

Just an FYI: I had to make one last correction in https://github.com/openpmix/prrte/pull/542/commits/794ff36f8476dbe55b61e05534f50b55759de15b to disable the errmgr/detector component by default as it was segfaulting during finalize. I believe the problem is that the `prte_errmgr_world_detector` structure is not being initialized (at least, I couldn't find a place where it happened).

**Pull request merged**
