### PR TITLE
Fix parsing regression.

### PR DESCRIPTION
**Pull request by awlauria**
I missed a few lines here:
https://github.com/openpmix/prrte/pull/736/

### CODE REVIEW

**Comment by rhc54** [comment]
I don't think anyone has touched those files in a decade - is this more PGI warning issues?

**Comment by awlauria** [comment]
@naughtont3 thanks for reporting. 
@rhc54 yeah it's a side effect of the pgi warnings fix. I missed a few break points.
If you prefer we can always revert the change and live with the warnings.

**Comment by rhc54** [comment]
No, this is fine - just the word "regression" implies that something changed so I was wondering what happened.

**Comment by rhc54** [comment]
Oh, I see it now over in Slack - sorry for the noise.

**Comment by naughtont3** [comment]
Works for me with `prte --help`

**Pull request merged**
