### PR TITLE
remove 'tar-ustar' format option to AM_INIT_AUTOMAKE

### PR DESCRIPTION
**Pull request by mblockso**
See discussion in https://github.com/openpmix/openpmix/pull/1771

@rhc54 @jsquyres

### CODE REVIEW

**Comment by jsquyres** [comment]
Hang on, I'm not convinced that this is the correct approach.  I'm doing some testing offline.

**Comment by mblockso** [comment]
No problem .. you guys are in control of the merge. :)

**Comment by jsquyres** [comment]
@mblockso Can you send the full stdout from running configure, the `config.log`, and the stdout/stderr from running `make dist` after your change to remove `tar-ustar`?

**Comment by mblockso** [comment]
```
# cd /home/mblockso/development/project/build/prrte
# /home/mblockso/development/project/source/prrte/configure --prefix=/home/mblockso/development/project/install --with-pmix=/home/mblockso/development/project/install 2>&1 | tee configure.txt
# mv config.log config_log.txt

# make dist 2>&1 | tee make.txt

# TAR_OPTIONS="--owner=0 --group=0 --numeric-owner" make dist 2>&1 | tee make_TAR_OPTIONS.txt
```
[configure.txt](https://github.com/openpmix/prrte/files/4663032/configure.txt)
[make_TAR_OPTIONS.txt](https://github.com/openpmix/prrte/files/4663034/make_TAR_OPTIONS.txt)
[make.txt](https://github.com/openpmix/prrte/files/4663035/make.txt)
[config_log.txt](https://github.com/openpmix/prrte/files/4663036/config_log.txt)

**Comment by jsquyres** [comment]
@mblockso Thank you!  I wanted to check your output to see if not specifying it would actually fall back to pax.  I'm out of time for today, but I'll check out your files tomorrow.  It also strikes me that I could probably find a stock container (or VM?) of some of the "problem" OSs and try out there to see what happens.

**Comment by jsquyres** [comment]
It looks like Automake has 3 ways to making tarballs:

1. `tar-ustar`: which we've been using forever (in OMPI/etc.), and has the known issue of the max UID, etc. that @mblockso identified.
    * Automake invokes `tar --format=ustar ...`
2. `tax-pax`: which @mblockso suggests (per the AM docs), but has the shortcoming that it doesn't work on older Net BSDs/etc.
    * Automake invokes `tar --format=pax ...`
3. (nothing specified)
    * Automake invokes `tar` without a `--format` option.  This apparently defaults to the `--format=gnu` option.

Did some testing with NetBSD, the problematic OS listed in the Automake docs:

| Tarball created with | Tried to extract on NetBSD 7.1.2 (March 2018) | Tried to extract on NetBSD 8.0.0 (July 2018) | Tried to extract on NetBSD 9.0.0 (Feb 2020) |
|---|---|---|---|
| Nothing (gnu) | Works | Works | Works |
| USTAR | Works | Works | Works |
| PAX | Does not work | Does not work | Works |

Hence, it seems like @mblockso's solution is the correct one: don't specify anything in the `AM_INIT_AUTOMAKE` line, and let Automake use the `gnu` format.  This is the most portable.

We should probably do this for all of our Open MPI family of projects.

(FWIW: it looks like we moved the main Open MPI project to use `tar-ustar` [in Jan of 2008](https://github.com/open-mpi/ompi/commit/a348da4eee7db969b5ab487c09e2efc4c77a3872), but the commit message doesn't say exactly why we did this.  😦 )

**Comment by jsquyres** [comment]
FWIW, the Travis build passed; not sure why Github is still showing that it's queued.

**Comment by mblockso** [comment]
@jsquyres .. Thanks! Now I don't have to maintain a local hack, I can just use master. Sweet!

**Pull request merged**
