### PR TITLE
Cleanup the PRRTE rpm spec file

### PR DESCRIPTION
**Pull request by rhc54**
Lots of stale cruft and bad naming errors from global
search-replace.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@jjhursey @awlauria Looks like the IBM CI may be stuck?

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
Looks like a Jenkins failure early. The retest is running now. I'll keep an eye on it while it runs.

**Comment by rhc54** [comment]
Thanks Josh!

**Pull request merged**
