### PR TITLE
Fix LSF configure check for libevent conflict

### PR DESCRIPTION
**Pull request by jjhursey**
* Want to make sure that the result from `wc` is trimmed of spaces, so the `0` check returns properly
 * Add a few more comments, and fix wording in the warning message.

### CODE REVIEW

**Comment by jjhursey** [comment]
@rhc54 Can you test this PR with your machine to make sure it fixes Issue #560 ? I'd like to get your 👍 before committing.

I tested on my mac (and on the target system) and it works fine now. I also cleaned up the warning message a bit for PRRTE.

**Comment by rhc54** [comment]
@jjhursey Probably need a modified form of this for openpmix too - we don't build against LSF, but still need to protect the libevent connection from the LSF version, yes?

**Comment by jjhursey** [comment]
Yeah we can add the check that I put into OMPI
 * https://github.com/open-mpi/ompi/pull/7749
It's only really helpful if the LSF libraries are in the default search path before the system installed version. It is helpful to catch none the less. I'll work up a PR today.

**Comment by jjhursey** [comment]
I PR'ed it here:
 * https://github.com/openpmix/openpmix/pull/1779

**Pull request merged**
