### PR TITLE
MPI 4.1: add support for memory-alloc-kinds

### PR DESCRIPTION
**Pull request by hppritcha**
Changes will need to be made to Open MPI to parse the contents of the OMPI_MCA_mpi_memory_alloc_kinds environment variable to determine how to use the user supplied memory-alloc-kinds information.

See section 11.4.3 of the MPI 4.1 standard.

### CODE REVIEW

**Comment by hppritcha** [comment]
@edgargabriel

**Comment by hppritcha** [comment]
hmm, looks like there's some issue with brew's install location for libevent and the pmix/prrte config options.

**Comment by hppritcha** [comment]
i think the brew install of libevent changed.  i'm noticing in the CI log that it thought libevent was already installed.

**Comment by rhc54** [comment]
@hppritcha You might take a gander at https://github.com/openpmix/openpmix/pull/3342 and https://github.com/openpmix/prrte/pull/1973 for an alternative implementation. Needed to support more than OMPI.

Once https://github.com/openpmix/prrte/pull/1973 is committed, you can poke this PR for retest and it should pass. I disabled the MacOS CI.

**Pull request merged**
