### PR TITLE
Use the info list array feature to construct registration data

### PR DESCRIPTION
**Pull request by rhc54**
Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
bot:ibm:pgi:retest

**Comment by rhc54** [comment]
@jjhursey The PGI failure appears to be real, but I cannot replicate it anywhere - so it may be something specific to that compiler. Is there any way you could get a line number as to where it is failing?

**Comment by jjhursey** [comment]
Yeah I'll see if I can get a stack trace for you today

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
The stack in the core file generated is corrupted.
```
(gdb) bt
#0  0x00007fffafc74308 in raise () from /usr/lib/gcc/ppc64le-redhat-linux/8/../../../../lib64/libc.so.6
#1  0x00007fffafc54484 in abort () from /usr/lib/gcc/ppc64le-redhat-linux/8/../../../../lib64/libc.so.6
#2  0x00007fffafcc095c in __libc_message () from /usr/lib/gcc/ppc64le-redhat-linux/8/../../../../lib64/libc.so.6
#3  0x00007fffafcca228 in malloc_printerr () from /usr/lib/gcc/ppc64le-redhat-linux/8/../../../../lib64/libc.so.6
#4  0x00007fffafcca66c in munmap_chunk () from /usr/lib/gcc/ppc64le-redhat-linux/8/../../../../lib64/libc.so.6
#5  0x00007fffb0d6d8e0 in prte_pmix_server_register_nspace () at prted/pmix/pmix_server_register_fns.c:3387
#6  0x0000000000000000 in ?? ()
```

This is repeatable - corrupted stack in the core file. I'm working on trying to attach to see if I can narrow it down.

**Comment by rhc54** [comment]
Must be badly corrupted as there is no line 3387 in `pmix_server_register_fns.c` - it only has 775 lines in it.

**Comment by jjhursey** [comment]
Right - that's part of the corruption.

Stepping through the function the crash happens at [line 551](https://github.com/openpmix/prrte/blob/ec07523e65ae116bc283133a15e822dcf83f0cf9/src/prted/pmix/pmix_server_register_fns.c#L551)
```
    PMIX_INFO_DESTRUCT(&devinfo[0]);
```

It's possible that the issue is higher up, and this is just the one place where it finally stepped over the line.

Since it is stack corruption I'm not sure if valgrind would help, but it might be a place to start.

**Comment by rhc54** [comment]
Aha - that actually is exactly what I needed! Much thanks for the assist!

**Comment by rhc54** [comment]
Odd that only PGI barfed on it - those info objects weren't being constructed/initialized, so we were destructing garbage. Guess just differences in how the stacks get initialized.

**Comment by jjhursey** [comment]
I'm glad that helped pinpoint it!

**Pull request merged**
