### PR TITLE
Make compilation of the resilient failure detector non-conditional

### PR DESCRIPTION
**Pull request by abouteiller**
Make compilation of the resilient failure detector non-conditional

change the name of the global control parameter for runtime enabling to
denote that it controls only fault detection/reporting capabilities, not
general FT

I have not removed the configure infrastructure for --with-ft because Ralph expressed interest in reusing it, but we do not depend on it anymore for the bmg/detector functionality hence it is available for reuse. 

Signed-off-by: Aurelien Bouteiller <bouteill@icl.utk.edu>

### CODE REVIEW

**Comment by rhc54** [comment]
I fixed the merge conflict. I think this is an okay starting point as it doesn't actually remove the conditional build of the UTK components. I have some additional changes that need to be made to achieve the desired isolation, but those can come afterwards. I'll coordinate with @bwbarrett prior to release to update the configure option so we can specify the FT strategy being enabled - that way, we'll maintain forward-compatibility over in OMPI.

**Comment by rhc54** [comment]
Quick note: the merge conflict was created by a commit you made that altered a section of the schizo/ompi component code. I assumed you wanted the code that was in master since that was your latest version. If that wasn't a correct assumption, then please change it to whatever you want it to be.

That code block gets revised in the upcoming CLI parser change as we no longer twiddle the argv, but I can handle that conflict. Just need to know what the resulting decision logic is supposed to be.

**Comment by abouteiller** [comment]
merge conflict resolution is correct, thanks

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
This is now out-of-date, so let's set it aside.

**Pull request closed without merging**
