### PR TITLE
Plug memory leaks.

### PR DESCRIPTION
**Pull request by samuelkgutierrez**

### CODE REVIEW

**Comment by samuelkgutierrez** [comment]
@rhc54 I need some help looking at the placement changes I made to `PRTE_REACHING_JOB_STATE` in this pull request. The updated placement seems to help with a memory leak, but I don't fully understand why. At least they are consistent with their usage in other nearby places, but I can't fully evaluate the implications of their updated placement. Can you please take a closer look at  the changed `PRTE_REACHING_JOB_STATE` spots? Thanks in advance.

**Comment by samuelkgutierrez** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
You definitely shouldn't move those `PRTE_REACHING_JOB_STATE` lines - looking at the code, I can't find anything that would involve a memory leak. Perhaps `valgrind` is in error (which sometimes happens)? What is the leak report causing the concern?

Just FWIW: we generally wouldn't worry that much about a memory leak in a debug statement as it doesn't execute in production code.

**Comment by samuelkgutierrez** [comment]
These are the additional leaks reported by Valgrind when my `PRTE_REACHING_JOB_STATE` changes are omitted:

```
==979189== 552 bytes in 1 blocks are definitely lost in loss record 360 of 402
==979189==    at 0x4844899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==979189==    by 0x49DD67F: pmix_tma_malloc (pmix_object.h:250)
==979189==    by 0x49DD94C: pmix_obj_new_tma (pmix_object.h:700)
==979189==    by 0x49DD6EB: pmix_obj_new_debug_tma (pmix_object.h:430)
==979189==    by 0x49DE270: prte_state_base_activate_job_state (state_base_fns.c:77)
==979189==    by 0x49E1FE5: prte_state_base_track_procs (state_base_fns.c:624)
==979189==    by 0x4A81281: ??? (in /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.7.0.1)
==979189==    by 0x4A82EEE: event_base_loop (in /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.7.0.1)
==979189==    by 0x112477: main (prte.c:1156)
==979189==    
==979189== 552 bytes in 1 blocks are definitely lost in loss record 361 of 402
==979189==    at 0x4844899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==979189==    by 0x49DD67F: pmix_tma_malloc (pmix_object.h:250)
==979189==    by 0x49DD94C: pmix_obj_new_tma (pmix_object.h:700)
==979189==    by 0x49DD6EB: pmix_obj_new_debug_tma (pmix_object.h:430)
==979189==    by 0x49DE270: prte_state_base_activate_job_state (state_base_fns.c:77)
==979189==    by 0x49EF5B0: check_complete (state_dvm.c:671)
==979189==    by 0x4A81281: ??? (in /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.7.0.1)
==979189==    by 0x4A82EEE: event_base_loop (in /usr/lib/x86_64-linux-gnu/libevent_core-2.1.so.7.0.1)
==979189==    by 0x112477: main (prte.c:1156)
```

I'll push an update without those changes for now, but will take a closer looking into why those are reported.

**Comment by rhc54** [comment]
Yeah, something else is going on - "reaching job state" is just a print statement, no memory being allocated. The trace claims the memory leak is due to creation of the caddy for actually processing the state change, not from printing it, so location of the print statement can't be causing the leak.

**Comment by samuelkgutierrez** [comment]
Okay, I'll see if I can find out what's going on.

**Comment by samuelkgutierrez** [comment]
After a little thought, I'm going to close this pull request and open another one without my messing with `PRTE_REACHING_JOB_STATE`; keep things a little more tidy.

**Pull request closed without merging**
