### PR TITLE
Pelist like cgroup

### PR DESCRIPTION
**Pull request by markalle**
This has two commits related to PE-LIST, the first has to do with parsing and the fact that PE-LIST is an option inside a comma separated list and it tries to have another comma separated list as its =value:

    PE-LIST parsing workaround, ex: --map-by core:pe=2,PE-LIST=1,2,3

    The PE-LIST option to --map-by doesn't really make sense since the
    items in the list of options to --map-by are comma separated and
    the PE-LIST can also have commas.

    The parsing function uses prrte_argv_split(ck, ',') which for
    the example case of
        --map-by core:pe=2,PE-LIST=1,2,3
    breaks the string into
        core
        pe=2
        PE-LIST=1
        2
        3

    I think this option was better off as --cpu-list, but I'm putting
    a few workarounds in:
    1. as long as PE-LIST is being parsed as a --map-by item, I have
       a special case where it accepts a comma separated list of
       numbers after PE-LIST as being together, not a separate
       --map-by item.
    2. allowing colons for a less ambiguous syntax in the PE-LIST so
       a person could use PE-LIST=1:2:3
    3. in schizo if --cpu-list 1,2,3 is used and it constructs a
       PE-LIST equivalent, it translates to 1:2:3 for less ambiguity

The second commit is about letting PE-LIST be used like a cgroup, to constrain what's available but not specifically force a binding policy itself, rather allow whatever binding the user specifies within the constrained machine, same thing that would happen in a cgroup.  And there was an error check that I think was too aggressive (intended for the rank-file case) that was stopping PE-LIST from being used.

    PE-LIST should't force BIND_TO_CPUSET if a binding is otherwise specified

    If PE-LIST is given then the binding was being set to PRRTE_BIND_TO_CPUSET,
    but I think that should only happen if a binding wasn't otherwise
    specified.  If a binding was given, it can still be used in the presence
    of PE-LIST, it's just that PE-LIST functions equivalently to a cgroup in
    that case, constraining what PU's are allowed.

    This PR uses hwloc_topology_restrict() to make the PE-LIST path work
    exactly like the cgroup case, if a binding was specified.  If a binding
    wasn't specified then it still lets the binding be set to
    PRRTE_BIND_TO_CPUSET like the code was doing before.

    There was also a too-aggressive error check in prrte_rmaps_rank_file_register()
    that was active not only in the case of a rankfile being used, but was also
    active if
        PRRTE_BIND_TO_CPUSET == PRRTE_GET_BINDING_POLICY(prrte_hwloc_binding_policy) &&
        !PRRTE_BIND_ORDERED_REQUESTED(prrte_hwloc_binding_policy)
    which was causing any use of BIND_TO_CPUSET to fail (eg the case of not
    specifying a binding but using PE-LIST, where BIND_TO_CPUSET gets set
    as the binding).

    Example failing command without the change to the above error check:
    % mpirun --np 2 --map-by core:,PE-LIST=4-99 ./pp.x
    > Conflicting directives for mapping policy are causing the policy
    > to be redefined:
    >   New policy:   RANK_FILE
    >   Prior policy:  BYCORE

### CODE REVIEW

**Comment by rhc54** [comment]
There are some pieces of this that might be useful, but this is a case where we again have to separate the setting of the topo to reflect an externally imposed envelope spanning the DVM versus a request to limit the cpu range of a specific job. I'll leave this PR open so we can harvest the usable pieces while we look at the best path forward.

**Comment by markalle** [comment]
I've been looking at this from the perspective of two issues:
1. mismatch between MCA setting hwloc_base_binding_policy and cmdline --bind-to
2. userdata->available and the constrained hwloc tree, persistent vs per-job

For item 1. by the time we call
  prrte_hwloc_base_register();
  prrte_hwloc_base_open();
the damage is done.  The binding policy gets set based on the MCA, and enough state is maintained that a subsequent call to hwloc_base_set_biding_policy(jdata...map) just makes the hwloc data inconsistent and it fails later in rmaps_base_compute_bindings().

So I think that still justifies my code that produced MCA settings based on cmdlines.  Eg if we see --bind-to on the cmdline we still need to set MCA_hwloc_base_binding_policy.  It would be in the per-job code, but that code still looks at MCAs so it still needs the MCA to represent the binding that it'll be doing.

I don't know specifically what pieces of hwloc data end up inconsistent, but if I run
% mpirun --map-by socket --bind-to hwthread:REPORT -np 2 hostname
The sequence of events is
```
prrte_init_util
    prrte_hwloc_base_register
    prrte_hwloc_base_open
        set_biding_policy
(then a little after that the other important part is)
prrte_init
    rte_init (prrte_ess.init)
        prrte_hwloc_base_get_topology()
            prrte_hwloc_base_filter_cpus()  // this is where userdata->available is used
```
all done in the persistent part of prte without use of --bind-to.

Later when we do get down to per-job stuff there's a call to set_binding_policy() but it doesn't reset enough to make the hwloc data consistent.  What I've had success with now is resetting hwloc for per-job: inside state_dvm.c I wasn't sure where, but I picked the end of vm_ready() since that seems to be the latest point before hwloc/binding stuff is about to get used, and to reset hwloc I ran
```
    setenv("PRRTE_MCA_hwloc_base_binding_policy", whatever_string_was_on_cmdline_bind_to, 1);
    prrte_hwloc_base_close();
    prrte_hwloc_base_register();
    prrte_hwloc_base_open();
    prrte_hwloc_base_get_topology();
```
And that was enough to rebuild hwloc back to a consistent state.  But it did require the MCA setting to be there because it uses that so early.

Item 2. is why I also included the base_get_topology() in the above.  I think we'd want the same thing to happen with the PE-LIST data being available as an MCA setting.

The old OMPI 3.x code was filled with checks of the userdata->available bitmap and skipping over unavailable elements when iterating.  A while back I was restoring that old code to bring back removed functionality, but the newer hwloc code that just uses a constrained tree rather than WHOLE_SYSTEM accomplishes the same thing much more cleanly and with less bugs.  So I'd definitely prefer a solution where the per-job PE-LIST completely resets the hwloc tree to the provided PUs so the rest of the code can stay simple.

I'm not positive now which part of my MCA/cmdline equivalency code was responsible for making the PE-LIST work, but I think it was the part that parsed --map-by stuff:PE-LIST=stuff and set MCA_hwloc_base_cpu_list.  If that's visible to base_var_register() it gets saved and used successfully.

**Comment by rhc54** [comment]
Leave it be, Mark - we are _not_ going to have cmd line options set MCA params. That is contrary to the PRRTE architecture. I've already been revising these areas to make it more visible as to what is going on (with comments etc) and will update when done.

**Comment by markalle** [comment]
I browsed how the hwloc_shmem is used, and would think it's still feasible to have both WHOLE_SYSTEM and restricted topology for the local host.

All I see the shmem doing is making the local host topology available in "hwloc.sm" for the OMPI ranks, and at that level I don't think I care if that one is WHOLE_SYSTEM or not.  It's the topology that gets walked inside prte's mapping/binding that has all the complicated code that I'd like to have walking a restricted tree.

To accomplish that I'd have
* prrte_hwloc_topology_persistent = loaded for whatever cgroup prte is in, put this one in hwloc.sm for the OMPI ranks to see
* prrte_hwloc_topology = reload on a per-job basis, restricted by cgroup/PE-LIST
* node->topology->topo = from remote prrte_hwloc_topology, signatures should get this reloaded as needed if you start in a different cgroup

And the only thing WHOLE_SYSTEM is needed for is the report-bindings, and at least currently each host is making its own report-bindings string so it only needs WHOLE_SYSTEM for the local host, not all the entries in remote node->topology->topo.

I'm still concerned about a complete switch to WHOLE_SYSTEM topologies due to how much more complex the 3.x code was.

**Pull request closed without merging**
