### PR TITLE
Try to do a better job of matching topos and nodes

### PR DESCRIPTION
**Pull request by rhc54**
Don't attempt to force the topo array to match on each
system - this can lead to errors as each node starts out
by putting its topology in index zero. Instead, do the
assignment based on signature, using the provided index
to find the corresponding signature and then identifying
the topology from that. This will only impact scalability
if there are a large number of topologies in the system,
which would be a very odd cluster indeed!

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
I _think_ this will fix #803 - @acolinisi could you please check/confirm?

**Comment by acolinisi** [comment]
A cursory test ends with a segfault of prted on one of the two compute nodes. But, the app completes on the other compute node. I'd have to get a stack trace for this to be of any use.

**Comment by rhc54** [comment]
I found it - fix coming in a bit

**Comment by rhc54** [comment]
@acolinisi Please give this another try when you have a chance.

**Comment by acolinisi** [comment]
This one works fine. Thank you.

**Comment by rhc54** [comment]
Hooray! Thanks for your patience!

**Pull request merged**
