### PR TITLE
Fix the LSF RAS component

### LINKED ISSUE #589: prrte build fails when lsf component is enabled
**Version**: prrte master

Here is the failure log:

```
ras_lsf_module.c:124:43: error: ‘prte_hwloc_binding_policy’ undeclared (first use in this function)
                PRTE_BINDING_POLICY_IS_SET(prte_hwloc_binding_policy)) {
                                           ^
/workspace/x86_64/ompi-73/build/ompi/prrte/src/hwloc/hwloc-internal.h:167:7: note: in definition of macro ‘PRTE_BINDING_POLICY_IS_SET’
     ((pol) & 0x4000)
       ^
ras_lsf_module.c:124:43: note: each undeclared identifier is reported only once for each function it appears in
                PRTE_BINDING_POLICY_IS_SET(prte_hwloc_binding_policy)) {
                                           ^
/workspace/x86_64/ompi-73/build/ompi/prrte/src/hwloc/hwloc-internal.h:167:7: note: in definition of macro ‘PRTE_BINDING_POLICY_IS_SET’
     ((pol) & 0x4000)
       ^
ras_lsf_module.c:149:48: error: ‘PRTE_JOB_PHYSICAL_CPUIDS’ undeclared (first use in this function)
         prte_set_attribute(&jdata->attributes, PRTE_JOB_PHYSICAL_CPUIDS, true, NULL, PRTE_BOOL);
                                                ^
ras_lsf_module.c:151:9: error: ‘prte_hwloc_use_hwthreads_as_cpus’ undeclared (first use in this function)
         prte_hwloc_use_hwthreads_as_cpus = true;
         ^
```

Looks like the changes in this PR is not ported to ras/lsf compoent.
https://github.com/openpmix/prrte/pull/555/files

### PR DESCRIPTION
**Pull request by jjhursey**
* Fix #589

### CODE REVIEW

**Comment by jjhursey** [comment]
In PR https://github.com/openpmix/prrte/pull/580 @rhc54 removed support for physical CPU IDs which breaks the current support for LSF's `LSB_AFFINITY_HOSTFILE` which provides the cpu mapping as physical hwthread ids.

I put in the fixes here to compile the code, and if a `LSB_AFFINITY_HOSTFILE` is present then an error is printed to the user.

I need to think a bit about how we might convert the file from physical to logical hwthread ids so it can be ingested by the rest of the system. Thus I'm going to leave this as a draft PR for now.

**Comment by rhc54** [comment]
Yeah, I had to pull the physical CPU support as it was becoming totally confused. HWLOC even confuses itself as some of the comments say "logical", but the behavior of the API is clearly "physical". Just became too much of a mess trying to keep everything straight. Only solution was to limit ourselves to one or the other (I chose logical since that is most of what HWLOC was using) and avoid the "physical" HWLOC constructs/APIs.

**Comment by rhc54** [comment]
@jjhursey Any progress on this?

**Comment by jjhursey** [comment]
Not much progress to note. But it is bubbling up to a higher priority for me.

**Comment by jjhursey** [comment]
A short term fix for this issue.

If we detect a `LSB_AFFINITY_HOSTFILE` with contents (which means that the user specified affinity to LSF) then we error out with this message:
```
--------------------------------------------------------------------------
The affinity file provided in LSB_AFFINITY_HOSTFILE could not be used:

  File:   /u/jjhursey/.lsbatch/1614724790.102784.hostAffinityFile
  Reason: Physical CPU ID mapping is not supported

Use the MCA parameter below to skip processing the LSB_AFFINITY_HOSTFILE
and ignore any binding provided by LSF for this job. Doing so may
require you to use the affinity options provided by PRTE.
  --mca ras_lsf_skip_affinity_file true
```

The user can then resubmit with that MCA parameter to continue running:
```
prterun --mca ras_lsf_skip_affinity_file true hostname
```

I will open a 'help wanted' issue to work on a solution to the `LSB_AFFINITY_HOSTFILE` and physical IDs.

**Comment by jjhursey** [comment]
This is ready for review. I tested on an LSF system and it works as expected.
See https://github.com/openpmix/prrte/issues/791 for the follow-on work.

**Review by rhc54 — APPROVED** [review]
The changes look okay to me

**Pull request merged**
