### PR TITLE
Convert PRRTE process names to PMIx process names

### PR DESCRIPTION
**Pull request by rhc54**
Eliminate the need to convert back/forth.

Change PRRTE job data back to a pointer array, thereby making cleanup easier.

Eliminate the DSS in favor of using PMIx data pack/unpack functions to
reduce code duplication.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
@jjhursey I'm going to need a little help here - these tests pass on my boxes (both Mac and Linux), so the segfault must have something to do with your environment. Can you get a more useful backtrace (with line numbers) for me?

**Comment by jjhursey** [comment]
Yeah, I'll build your branch and see if I can get you a proper stack trace from one of the core files. It won't be until tomorrow probably.

**Comment by jjhursey** [comment]
I grabbed a debug build, and ran with 1 node (no hostfile)
```
shell$ cd prrte/hello_world/
shell$ ./build.sh
shell$ prte --no-ready-msg &
shell$ prun --map-by ppr:5:node hostname
c712f6n01
c712f6n01
c712f6n01
c712f6n01
prte: attr.c:675: prte_attr_unload: Assertion `0' failed.
c712f6n01
[1]+  Aborted                 (core dumped) prte --no-ready-msg
shell$ gdb prte --core core.85041
(gdb) bt
#0  0x00003fff8029fc30 in raise () from /lib64/libc.so.6
#1  0x00003fff802a1f00 in abort () from /lib64/libc.so.6
#2  0x00003fff80295754 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00003fff80295844 in __assert_fail () from /lib64/libc.so.6
#4  0x00003fff80d11d98 in prte_attr_unload (kv=0x10039319b20, data=0x3fffeccec140, type=22) at attr.c:675
#5  0x00003fff80d0fac8 in prte_get_attribute (attributes=0x1003931dcf0, key=240, data=0x3fffeccec140, type=22) at attr.c:55
#6  0x00003fff80119a00 in dvm_notify (sd=-1, args=4, cbdata=0x10039340df0) at state_dvm.c:815
#7  0x00003fff80916cb8 in event_process_active_single_queue (base=0x100391e5890, activeq=0x100391e5f40, max_to_process=2147483647, 
    endtime=0x0) at event.c:1646
#8  0x00003fff809177a4 in event_process_active (base=0x100391e5890) at event.c:1738
#9  event_base_loop (base=0x100391e5890, flags=<optimized out>) at event.c:1961
#10 0x000000001000921c in main (argc=2, argv=0x3fffeccee108) at prte.c:1195
(gdb) up
#1  0x00003fff802a1f00 in abort () from /lib64/libc.so.6
(gdb) 
#2  0x00003fff80295754 in __assert_fail_base () from /lib64/libc.so.6
(gdb) 
#3  0x00003fff80295844 in __assert_fail () from /lib64/libc.so.6
(gdb) 
#4  0x00003fff80d11d98 in prte_attr_unload (kv=0x10039319b20, data=0x3fffeccec140, type=22) at attr.c:675
675	        assert(0);
(gdb) l
670	        return PRTE_ERR_TYPE_MISMATCH;
671	    }
672	    if (NULL == data  ||
673	        (PMIX_STRING != type && PMIX_BYTE_OBJECT != type &&
674	         PMIX_BUFFER != type && PMIX_POINTER != type && NULL == *data)) {
675	        assert(0);
676	        PRTE_ERROR_LOG(PRTE_ERR_BAD_PARAM);
677	        return PRTE_ERR_BAD_PARAM;
678	    }
(gdb) p type
$1 = 22
(gdb) p data
$2 = (void **) 0x3fffe9fd4040
(gdb) p *data
$3 = (void *) 0x0
(gdb) up
#5  0x00003fff87b2fac8 in prte_get_attribute (attributes=0x100098cdcf0, key=240, data=0x3fffe9fd4040, type=22) at attr.c:55
55	                if (PRTE_SUCCESS != (rc = prte_attr_unload(kv, data, type))) {
(gdb) p *kv
$4 = {
  super = {
    super = {
      obj_magic_id = 16046253926196952813, 
      obj_class = 0x3fff87c31bc8 <prte_attribute_t_class>, 
      obj_reference_count = 1, 
      cls_init_file_name = 0x3fff87be58d0 "runtime/data_type_support/prte_dt_unpacking_fns.c", 
      cls_init_lineno = 109
    }, 
    prte_list_next = 0x100098ca8d0, 
    prte_list_prev = 0x10009884ac0, 
    item_free = 1, 
    prte_list_item_refcount = 1, 
    prte_list_item_belong_to = 0x100098cdcf0
  }, 
  key = 240, 
  local = false, 
  data = {
    type = 22, 
    data = {
      flag = 160, 
      byte = 160 '\240', 
      string = 0x100098ca7a0 "prte-c712f6n01-85572@1", 
      size = 1099671840672, 
      pid = 160212896, 
      integer = 160212896, 
      int8 = -96 '\240', 
      int16 = -22624, 
      int32 = 160212896, 
      int64 = 1099671840672, 
      uint = 160212896, 
      uint8 = 160 '\240', 
      uint16 = 42912, 
      uint32 = 160212896, 
      uint64 = 1099671840672, 
      fval = 3.38614078e-33, 
      dval = 5.4331007817504405e-312, 
      tv = {
        tv_sec = 1099671840672, 
        tv_usec = 0
      }, 
      time = 1099671840672, 
      status = 160212896, 
      rank = 160212896, 
      nspace = 0x100098ca7a0, 
      proc = 0x100098ca7a0, 
      bo = {
        bytes = 0x100098ca7a0 "prte-c712f6n01-85572@1", 
        size = 0
      }, 
      persist = 160 '\240', 
      scope = 160 '\240', 
      range = 160 '\240', 
      state = 160 '\240', 
      pinfo = 0x100098ca7a0, 
      darray = 0x100098ca7a0, 
      ptr = 0x100098ca7a0, 
      adir = 160 '\240', 
      envar = {
        envar = 0x100098ca7a0 "prte-c712f6n01-85572@1", 
        value = 0x0, 
        separator = 0 '\000'
      }, 
      coord = 0x100098ca7a0, 
      linkstate = 160 '\240', 
      jstate = 160 '\240', 
      topo = 0x100098ca7a0, 
      cpuset = 0x100098ca7a0, 
      locality = 42912, 
      geometry = 0x100098ca7a0, 
      devtype = 1099671840672, 
      devdist = 0x100098ca7a0, 
      endpoint = 0x100098ca7a0, 
      dbuf = 0x100098ca7a0, 
      pstats = 0x100098ca7a0, 
      dkstats = 0x100098ca7a0, 
      netstats = 0x100098ca7a0, 
      ndstats = 0x100098ca7a0
    }
  }
}
```

I ran with 3 nodes and hit the same issue with hello world. I can try to recreate with the CI infrastructure to isolate that core dump to see if it's different.

**Comment by rhc54** [comment]
I believe I fixed that `assert` you hit, but that can't be the original problem as that manifested with a non-debug build. Let's see what happens with this revision.

**Comment by jjhursey** [comment]
I'm in a close environment to CI and am having trouble hitting the issue. Let me see if I can get CI to trip it with some more information...
bot:ibm:gnu:retest

**Comment by jjhursey** [comment]
I managed to get access to the core, and this is what it shows:
```
Core was generated by `prte --no-ready-msg --hostfile /workspace/hostfile.txt '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fff8c9845dc in push_stdin (dst_name=0x7fff880a0030, data=0x7fff88001a10 "\320\027\004\210\377\177", sz=0)
    at iof_hnp.c:242
242	    if (PMIX_CHECK_PROCID(PRTE_PROC_MY_NAME, &proct->stdinev->daemon)) {
[Current thread is 1 (Thread 0x7fff8f877ce0 (LWP 13))]
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-101.el8.ppc64le libxml2-2.9.7-7.el8.ppc64le xz-libs-5.2.4-3.el8.ppc64le zlib-1.2.11-13.el8.ppc64le
(gdb) bt
#0  0x00007fff8c9845dc in push_stdin (dst_name=0x7fff880a0030, data=0x7fff88001a10 "\320\027\004\210\377\177", sz=0)
    at iof_hnp.c:242
#1  0x00007fff8f6cb7e4 in pmix_server_stdin_push (sd=-1, args=4, cbdata=0x7fff880a0140) at prted/pmix/pmix_server_gen.c:1259
#2  0x00007fff8f2d9e24 in event_process_active_single_queue (base=base@entry=0x100082e4ac0, activeq=0x100082e5070, 
    max_to_process=max_to_process@entry=2147483647, endtime=endtime@entry=0x0) at event.c:1691
#3  0x00007fff8f2da9b0 in event_process_active (base=0x100082e4ac0) at event.c:1783
#4  event_base_loop (base=0x100082e4ac0, flags=<optimized out>) at event.c:2006
#5  0x000000001000991c in main (argc=4, argv=0x7fffcc190398) at prte.c:1195
(gdb) p proct
$1 = (prte_iof_proc_t *) 0x100084dd2a0
(gdb) p proct->stdinev
$2 = (prte_iof_sink_t *) 0x0
(gdb)  p *proct
$3 = {
  super = {
    super = {
      obj_magic_id = 16046253926196952813, 
      obj_class = 0x7fff8f804558 <prte_iof_proc_t_class>, 
      obj_reference_count = 3, 
      cls_init_file_name = 0x7fff8c98be68 "iof_hnp.c", 
      cls_init_lineno = 150
    }, 
    prte_list_next = 0x1000854f6f0, 
    prte_list_prev = 0x100084dc300, 
    item_free = 1, 
    prte_list_item_refcount = 1, 
    prte_list_item_belong_to = 0x7fff8c9a0320 <prte_iof_hnp_component+264>
  }, 
  name = {
    nspace = "prte-9c61131c06cb-13@4", '\000' <repeats 233 times>, 
    rank = 0
  }, 
  stdinev = 0x0, 
  revstdout = 0x100084f45b0, 
  revstderr = 0x100084f18b0, 
  subscribers = 0x100084f1f60, 
  copy = true
}
```

**Comment by jjhursey** [comment]
I figured out how to reproduce. From that stack it looks like the stdin channel is NULL. So I tried:
```
prte --no-ready-msg --hostfile /workspace/hostfile.txt &
prun --map-by ppr:5:node ./hello < /dev/null 
prun --map-by ppr:5:node ./hello < /dev/null 
```
The first will run fine, the second will segv.

I added `--prtemca iof_base_verbose 100` to the `prte` command and put the output in the Gist below:
 * https://gist.github.com/jjhursey/0fcf6796d86b9429dda45ee820e6381b

**Comment by rhc54** [comment]
Not sure I understand - what is the difference between those two invocations?

**Comment by jjhursey** [comment]
There is nothing different between them. I suspect something is being carried over from the completion of the first `prun` that messes up the second. I'm not sure though.

**Comment by rhc54** [comment]
The debug tests are completing correctly, but the fingerprint obviously isn't correct given the change in naming protocol. I've tried to regenerate it, but the program for doing so just hangs for me.

**Pull request merged**
