### PR TITLE
RTD: Add .readthedocs.yaml file

### PR DESCRIPTION
**Pull request by lrbison**

### CODE REVIEW

**Comment by rhc54** [comment]
Going to need this cherry-picked to the v3.0 and v3.1 branches, once committed here. I can do it, or you are welcome to do so.

**Comment by rhc54** [comment]
bot:ibm:retest

Tue May 9 14:07:09 UTC 2023

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by samuelkgutierrez** [comment]
bot:ibm:retest

**Pull request merged**
