### PR TITLE
Fix typo quoting for prefixed daemon launches

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by jjhursey** [comment]
It's been in there a little while too. I'm not sure how we didn't trip over this earlier.

**Comment by rhc54** [comment]
I suspect nobody has been using the ```--prefix``` option? I usually just enable prefix-by-default, so that doesn't trip over this one.

**Comment by jjhursey** [comment]
In our runs we were not explicitly using the `--prefix`, but it must have been triggered when using the absolute path vs relative path to the binary. Which makes sense to me.

**Comment by rhc54** [comment]
I can update the pointer in OMPI

**Pull request merged**
