### PR TITLE
Fix attached tool job term notice

### PR DESCRIPTION
**Pull request by jjhursey**
* In a non-persistent run (`prterun`) we could have a tool attached
   to `prterun` waiting for the job termination notification. This
   patch detects the presence of a tool and issues the notification before
   shutting down.
   - The MPIR Shim has an attach mode that found this issue. It would
     get a general connection lost event instead of the job terminated
     event in this case.

### CODE REVIEW

**Comment by jjhursey** [comment]
I'm not 100% sure this is the right way to do this, but it works for our use case:

### Terminal A

`sleeper` is an MPI application that will wait in a busy loop until a debugger attaches and releases it (simulating a hung process).
```
mpirun -np 2 ./sleeper 1
```

### Terminal B

Using MPIR Shim from https://github.com/openpmix/mpir-shim/pull/18 (`123` is the PID of `mpirun`)
```
mpir -d --attach 123
```

### Terminal C

Attach to the `sleeper` processes with `gdb` and release them from their wait loop.

Then make sure that `mpir` in Terminal B is seeing the `PMIX_ERR_JOB_TERMINATED` event with the exit status of the application. And that exit status matches that of `mpirun` in Terminal A.

**Comment by jjhursey** [comment]
Adding WIP - now I'm not seeing the correct exit_status from the notification. I'm looking into it.

**Comment by jjhursey** [comment]
Ok I sorted it out as a bug in the mpir shim code. I've fixed that and now we see the correct error code.

**Comment by rhc54** [comment]
Makes sense - thx!

**Pull request merged**
