### PR TITLE
ompi/schizo: Fix some options

### PR DESCRIPTION
**Pull request by awlauria**
Map them to the new --runtime-options option.

Signed-off-by: Austen Lauria <awlauria@us.ibm.com>

### CODE REVIEW

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
If it helps, and depending on what you want for cmd line options, I am adding a "parse_rtos" function that takes the string passed to `--runtime-options` and breaks it down into its PMIx parts for passing to PRRTE. Hope to have it committed later today.

**Comment by rhc54** [comment]
FWIW: here is the list of CLI that are served by the `runtime-options` directive:
```c
#define PRTE_CLI_ABORT_NZ           "abort-nonzero-status"          // optional arg
#define PRTE_CLI_NOLAUNCH           "donotlaunch"                   // no arg
#define PRTE_CLI_SHOW_PROGRESS      "show-progress"                 // optional arg
#define PRTE_CLI_RECOVER            "recover"                       // optional arg
#define PRTE_CLI_MAX_RESTARTS       "max-restarts"                  // reqd arg
#define PRTE_CLI_EXEC_AGENT         "exec-agent"                    // reqd arg
#define PRTE_CLI_STOP_ON_EXEC       "stop-on-exec"                  // optional arg
#define PRTE_CLI_STOP_IN_INIT       "stop-in-init"                  // optional arg
#define PRTE_CLI_STOP_IN_APP        "stop-in-app"                   // optional arg
#define PRTE_CLI_TIMEOUT            "timeout"                       // reqd arg
#define PRTE_CLI_SPAWN_TIMEOUT      "spawn-timeout"                 // reqd arg
#define PRTE_CLI_REPORT_STATE       "report-state-on-timeout"       // optional arg
#define PRTE_CLI_STACK_TRACES       "get-stack-traces"              // optional arg
#define PRTE_CLI_REPORT_CHILD_SEP   "report-child-jobs-separately"  // optional arg
#define PRTE_CLI_AGG_HELP           "aggregate-help"                // optional arg
```
donotlaunch has no argument because you cannot give it a default value. Others have optional args that can either be bool (so you can override a default value), or in some cases strings - the parser checks to see what was given and does the right thing.

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by awlauria** [comment]
@rhc54 thanks - yeah maybe it would be best to wait for that so I can wire it in here.

**Comment by rhc54** [comment]
Sorry for delay - been deluged with other issues that required my input and/or coding. Will return to this over the weekend.

**Comment by awlauria** [comment]
Hey @rhc54 I was out most of this week, where does this PR stand?

**Comment by rhc54** [comment]
I believe it will work as it stands - not optimal and the help files still need updating, but it should function. I'd suggest we re-test to confirm that statement.

I'm trying to track down a strange problem right now, but it (probably?) shouldn't stand in the way. Let's give the tests a try.

bot:ibm:retest

**Comment by awlauria** [comment]
Did the code change go in to make this cleaner/more optimal? I can update it if so.

**Comment by rhc54** [comment]
Yes, but let me explain a bit so you can see if you want to change or not. I added the `--runtime-options` CLI that aggregates the things I listed before. So you can, if you choose, assemble those options into the PMIX_RUNTIME_OPTIONS attribute and pass them there.

However, since the PMIx client calling PMIx_Spawn can be from any prior version that wouldn't include that attribute, PRRTE continues to support the individual attributes as well. So you don't need to change anything - PRRTE will handle it either way.

Only catch is that the centralized help files are based on use of the new PMIX_RUNTIME_OPTIONS attribute, so you'd have to maintain your own version. Just depends on what you consider easiest for you.

Going forward, any new runtime options would probably rely on the new attribute instead of continuing to define individual ones. The Standards group is wrestling with this a bit right now. The pro is that it avoids adding attributes that might define things that could be considered implementation-specific. Argument the other way is that the list of attributes gets rather long, and you still need some way to pass attributes that are unique to the runtime environment in which you find yourself.

Not sure how all that will resolve. I'm guessing that we will wind up with a combination - individual attributes that describe a common behavior that can be clearly articulated - e.g., STOP_ON_EXEC. Retain a generic attribute for passing something that you know isn't portable, but you need to provide to this environment.

So choice is truly up to you. I updated the schizo/prte component, fwiw.

**Comment by rhc54** [comment]
Looks good in test - so let me know if you want to commit as-is for now.

**Comment by awlauria** [comment]
@rhc54 so the way I understand it we shouldn't need to change any options to map to the new RTO's? If that is the case, I think I'll edit this PR to remove those changes.

**Comment by rhc54** [comment]
I think that won't be true as options are changing. Let me complete the latest update and let's reevaluate.

**Comment by rhc54** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
I think we are going to need to make the changes, so once this passes CI I'll commit it so we don't create conflicts. I hope to finish the FT update today, assuming I can sit long enough to do so. Otherwise, it'll be tomorrow. I'll update the schizo/ompi as part of it, or at least add comments pointing out what needs to be done if I can't do it.

**Pull request merged**
