### PR TITLE
Fix minor issues found in tests.

### PR DESCRIPTION
**Pull request by samuelkgutierrez**
* Don't accidentally remove source files in make clean
* Silence compiler warnings

Signed-off-by: Samuel K. Gutierrez <samuel@lanl.gov>

### CODE REVIEW

**Comment by samuelkgutierrez** [comment]
Please note there remains another warning that requires attention. It's not immediately obvious to me how to fix it. 

```
connect.c:68:22: warning: passing argument 1 of ‘PMIx_Load_nspace’ from incompatible pointer type [-Wincompatible-po
  inter-types]                                                                                                        
     68 |     PMIX_LOAD_NSPACE(&remote, myproc.nspace);                                                               
        |                      ^~~~~~~                                                                                
        |                      |                                                                                      
        |                      pmix_proc_t * {aka struct pmix_proc *}                                                 
  /home/samuel/local/pmix/include/pmix_deprecated.h:483:22: note: in definition of macro ‘PMIX_LOAD_NSPACE’           
    483 |     PMIx_Load_nspace(a, b)                                                                                  
        |                      ^                                                                                      
  /home/samuel/local/pmix/include/pmix_deprecated.h:215:49: note: expected ‘char *’ but argument is of type ‘pmix_proc
  _t *’ {aka ‘struct pmix_proc *’}                                                                                    
    215 | PMIX_EXPORT void PMIx_Load_nspace(pmix_nspace_t nspace, const char *str);  
```

**Comment by rhc54** [comment]
>      68 |     PMIX_LOAD_NSPACE(&remote, myproc.nspace);                                                               

Should be:
```c
PMIX_LOAD_NSPACE(remote.nspace, myproc.nspace);
```

**Comment by rhc54** [comment]
I can't figure out what is wrong with the "attach" test on ppc64 - we'll just ignore it if it continues to fail. Works fine for me, so I think this is something machine-specific over there. Output looks right, don't know why the diff is complaining.

**Comment by rhc54** [comment]
Well, at least the CI was now consistent - they all fail on diff of the "attach" output! We'll try it one more time.

bot:ibm:retest

**Pull request merged**
