### PR TITLE
Support fix for OMPI Github issue #11532

### PR DESCRIPTION
**Pull request by qkoziol**
Support fix in OMPI by creating an installed header file for the frameworks that PRRTE is built with, so that any legacy framework parameters can be translated by OMPI.

Also refactor parameter translation routine into a separate routine to make it easier to copy into OMPI and maintain concurrently in both packages.

Addresses issue https://github.com/open-mpi/ompi/issues/11532, and supports OMPI PR: https://github.com/open-mpi/ompi/pull/11854

### CODE REVIEW

**Comment by qkoziol** [comment]
bot:retest

**Comment by awlauria** [comment]
bot:ibm:retest

**Comment by gpaulsen** [comment]
bot:ibm:retest

**Comment by qkoziol** [comment]
Revised to only include the refactor on the translate_param() functionality.

**Comment by rhc54** [comment]
bot:ibm:retest

**Pull request merged**
