### PR TITLE
CI Testing

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by rhc54** [comment]
Will CI run on a draft PR?

**Comment by jjhursey** [comment]
Yeah it looks like it will. CI was just backed up :(

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
CI is looking clean now that we downgraded to hwloc 2.4.0. https://github.com/open-mpi/hwloc/pull/514 was filed or the issue we hit with `ZES_ENABLE_SYSMAN`

**Pull request closed without merging**
