### PR TITLE
Fix max_slots for hostfiles

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by jjhursey** [comment]
Left to do:
 * Round Robin `span` is not covered
 * Review other mappers to add the logic to check for max_slots

**Comment by jjhursey** [comment]
Note to self on test case:
```
$ cat max-slots-hostfile.txt
c712f6n01 slots=4 max_slots=4
c712f6n02         max_slots=4
c712f6n03 slots=4
```

Testing `--map-by slot` (This is working now)
```
prterun --hostfile ./max-slots-hostfile.txt --np 19 --map-by slot:OVERSUBSCRIBE:DISPLAYALLOC --bind-to :REPORT hostname
```

Testing `--map-by node` (This is working now)
```
prterun --hostfile ./max-slots-hostfile.txt --np 19 --map-by node:OVERSUBSCRIBE:DISPLAYALLOC --bind-to :REPORT hostname
```

Testing `--map-by core` (This is working now)
```
prterun --hostfile ./max-slots-hostfile.txt --np 19 --map-by core:OVERSUBSCRIBE:DISPLAYALLOC --bind-to :REPORT hostname
```

Testing `:SPAN` (This is the one that is missing)
```
 prterun --hostfile ./max-slots-hostfile.txt --np 14 --map-by package:OVERSUBSCRIBE:DISPLAYALLOC:SPAN --bind-to :REPORT hostname
```

**Comment by jjhursey** [comment]
I probably won't be able to finish this before I leave later today. I'll keep working on it next week unless someone is eager to help in the meantime.

**Comment by jjhursey** [comment]
This PR is not 100% done, but I don't have the ability to push on it any further.

What is working:
 * `--map-by slot`
 * `--map-by node`
 * `--map-by core`

What is not working:
 * `:SPAN`
   * I started working on adding the `max_slots` logic in there, but found a more general issue with the mapping/ranking of processes with `:SPAN` across nodes when _not_ using `max_slots`. I was able to reproduce with 3 nodes, and a different number of slots per node.

The community could take this in as a fix for most cases, then work on the `:SPAN` issue separately.

**Comment by awlauria** [comment]
Should this be brought in and then SPAN can come in later?

**Comment by rhc54** [comment]
Probably - can't see any real reason to delay. I'd have to look at the issue being cited in the above comment, but that is a separate matter.

**Pull request merged**
