### PR TITLE
pass prefix down from prun to prte

### PR DESCRIPTION
**Pull request by naughtont3**
refs #371

Signed-off-by: Thomas Naughton <naughtont@ornl.gov>

### CODE REVIEW

**Comment by rhc54** [comment]
This seems odd - we explicitly use the prefix to set an absolute path on the `prte` command line. `prte` is supposed to pick that up and use it as its prefix. Setting it also as `--prefix foo` shouldn't be necessary - it sounds like there is actually a bug in `prte` and how it handles absolute path names.

**Comment by naughtont3** [comment]
@rhc54 I think `prte` picks it up properly.  It is just that the `--prefix FOO` was stripped from the argv we pass down to the `prte`.

**Comment by rhc54** [comment]
But my point is that we used the `prefix` to create the cmd `<prefix>/prte` and used that as the cmd we executed. So `prte` is supposed to look at its argv[0], see that it was an absolute path, and continue accordingly. Effectively, using the absolute path is supposed to be equivalent to passing `--prefix foo`. Hence my question.

**Comment by naughtont3** [comment]
Oh, ok.  I see what you're saying. So fully-qualified `prte` path should be equivalent to passing the `--prefix` to `prte`.

**Comment by naughtont3** [comment]
I'll look into that now and fix that way.

**Comment by naughtont3** [comment]
Closing b/c #384 was merged and this variant not needed.

**Pull request closed without merging**
