### PR TITLE
Cleanup schizo/prte help files

### PR DESCRIPTION
**Pull request by rhc54**
Get the PRRTE version to appear correctly in the
usage headers. Initialize the required globals
in pterm. Update the help files themselves.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
Hmmm...looks like infrastructure failure.

bot:ibm:retest

**Comment by rhc54** [comment]
Not sure if this ran again:

Wed Nov 2 19:56:27 UTC 2022

bot:ibm:retest

**Comment by rhc54** [comment]
@jjhursey Can you help me out here a bit? The tests are getting to the "run" phase for dmodex, and then everything just stops. This is just help file stuff, so I doubt it is impacting dmodex - can you see what is happening?

**Comment by jjhursey** [comment]
I'm not sure why it isn't appearing in the gist log, but here is the error:
```
==========================
PMIx dmodex build
==========================
+ FINAL_RTN=0
+ PRTEPID=0
+ NUM_NODES=3
+ cat /opt/mpi/etc/hostfile
+ xargs -L1 -I '{}' ssh '{}' rm -rf /tmp/prte.ci-prrte-pgi-upstream-cluster-login-552pq.59674
+ prterun --hostfile /opt/mpi/etc/hostfile --map-by ppr:10:node --leave-session-attached ./dmodex
+ tee output.txt
--------------------------------------------------------------------------
An unrecognized option was included on the prted command line:

  Option: --leave-session-attached

Please use the "prted --help" command to obtain a list of all
supported options.
--------------------------------------------------------------------------
[ci-prrte-pgi-upstream-cluster-login-552pq:76346] UNSUPPORTED DAEMON ERROR STATE: FAILED TO START
--------------------------------------------------------------------------
An unrecognized option was included on the prted command line:

  Option: --leave-session-attached

Please use the "prted --help" command to obtain a list of all
supported options.
--------------------------------------------------------------------------
[ci-prrte-pgi-upstream-cluster-login-552pq:76346] UNSUPPORTED DAEMON ERROR STATE: FAILED TO START
--------------------------------------------------------------------------
An unrecognized option was included on the prted command line:

  Option: --leave-session-attached

Please use the "prted --help" command to obtain a list of all
supported options.
--------------------------------------------------------------------------
[ci-prrte-pgi-upstream-cluster-login-552pq:76346] UNSUPPORTED DAEMON ERROR STATE: FAILED TO START
```

Maybe this part of the test needs to change?
 * https://github.com/openpmix/pmix-tests/blob/27369c3b81ae870c5bb47c50c1189485a5dc256f/prrte/dmodex/run.sh#L27-L36

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
I think I fixed the IBM backend script so it should show the error next time (if it happens again). But the testing looks better this interation

**Pull request merged**
