### PR TITLE
Add --display-comm{-finalize} to OMPI CLI

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by jjhursey** [comment]
Open MPI community requested this CLI option. Companion PR (though they are not dependent) https://github.com/open-mpi/ompi/pull/8313

I choose `-prot` and `-protlazy` since those are the CLI names that Spectrum MPI uses.

**Review by awlauria — APPROVED** [review]

**Comment by jjhursey** [comment]
Per Open MPI Teleconf Jan. 5, 2021:
 * Put this out for comment.
 * If no objections then we will merge on Jan. 12, 2021 after OMPI teleconf.

**Comment by jjhursey** [comment]
Requires https://github.com/open-mpi/ompi/pull/8313 from OMPI to work - otherwise, it is ignored.

**Comment by abouteiller** [comment]
Looks good but I'm not a big fan of the option name. `protlazy` looks like a control rather than a debug/display control.

What about `--display-comm` and `display-comm-finalize`, for uniformity with `display-map` ?

**Comment by jjhursey** [comment]
> What about `--display-comm` and `display-comm-finalize`, for uniformity with `display-map` ?

I like that. Keeps it consistent with the other `--display` reporting options.

**Comment by jjhursey** [comment]
I just pushed the adjustment to rename it from -prot/-protlazy to --display-comm/--display-comm-finalize

**Review by awlauria — APPROVED** [review]

**Pull request merged**
