### PR TITLE
CLI cleanups

### PR DESCRIPTION
**Pull request by rajachan**
```
commit 4e324b5e369b120bb0386aebb3d4fcc8d55ad89f
Author: Raghu Raja <craghun@amazon.com>
Date:   Mon Mar 8 07:01:09 2021 +0000

    Limit --default-hostfile to prterun and prte

    This specifies the total set of machines available which is useful for
    unmanaged environments. The --hostfile/--host options can choose a
    subset from this larger set. This option is meant to be global in
    nature, and set by an admin or whoever controls the job launch in the
    allocation.

    Ref: https://github.com/openpmix/prrte/issues/709

    Signed-off-by: Raghu Raja <craghun@amazon.com>

commit 605313ad7997b61e25afd57bec8a576e0fed69fe
Author: Raghu Raja <craghun@amazon.com>
Date:   Tue Feb 16 00:55:49 2021 +0000

    prte: Remove stale CLI options.

    Remove report-pids, do-not-resolve, and index-argv-by-rank CLI options.

    Ref: https://github.com/openpmix/prrte/issues/709

    Signed-off-by: Raghu Raja <craghun@amazon.com>
```

### CODE REVIEW

**Comment by jjhursey** [comment]
For man page cleanup, please requirest changes on https://github.com/openpmix/prrte/pull/773 so they are not lost.

**Comment by rhc54** [comment]
@jjhursey Do you want me to hold off this commit?

**Comment by jjhursey** [comment]
I just merged PR #773 so this will need to be rebased to fix the prtun.1.md conflict. Then I think it's good to go.

**Review by jjhursey — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
