### PR TITLE
ompi schizo: remove some unsupported options

### PR DESCRIPTION
**Pull request by hppritcha**
from the mpirun help message

related to https://github.com/open-mpi/ompi/issues/10705

Signed-off-by: Howard Pritchard <howardp@lanl.gov>

### CODE REVIEW

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by rhc54** [comment]
Hmmm...when you say "unsupported args", do you mean "args we are not going to expose to the average user"? For example, the tools people definitely need options like `--report-uri` and `--keepalive` (so `mpirun` can terminate if the tool dies). There are others you are removing that fit into these categories as well.

Might want to scrub this list again with the tools folks in mind.

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by hppritcha** [comment]
@jjhursey I think we need to re-review the contents of https://github.com/open-mpi/ompi/issues/10705 at next ompi devel meeting.

**Comment by awlauria** [comment]
@hppritcha I think this is taken care of by https://github.com/openpmix/prrte/pull/1542

**Comment by jjhursey** [comment]
Per discussion with Austen this should be covered by a prior PR. We will re-review the OMPI ticket to make sure everything is covered.

**Pull request closed without merging**
