### PR TITLE
Restructure code to avoid symbol conflicts with OMPI

### PR DESCRIPTION
**Pull request by rhc54**
In preparation for the OMPI community's planned adoption of PRRTE as
their embedded runtime, we need to rename all symbols to avoid conflicts
with OMPI's use of OPAL. PRRTE utilizes only a tiny part of OPAL, so
there really isn't much benefit to forcing co-existence of the two
codes. Much easier to just eliminate the problem by changing the PRRTE
symbols.

Given that requirement, collapse the OPAL/ORTE layers into a single
unified code base under a new "src" directory. Rename both ORTE and OPAL
symbols to their PRRTE equivalents. Remove all stale code that
referenced PRRTE-based applications and tools as those do not exist -
all tools in the PRRTE code base are purely PMIx-based except for some
minor use of PRRTE utilities (e.g., the object system to support lists).

Remove the debugger_flags configury as PRRTE does not support MPIR.
Remove a few stale .m4 files that do not pertain to PRRTE. Use the
wrapper_flags_add macro to add the hwloc, libev/event, and pmix wrapper
flags and libraries to keep things abstracted. Ensure that pcc does NOT
include CPPFLAGS/LDFLAGS for PRRTE as apps are not allowed to link
against it.

Signed-off-by: Ralph Castain <rhc@pmix.org>

### CODE REVIEW

**Comment by rhc54** [comment]
Massive restructuring of the PRRTE code base - still need to complete work on the prted daemon itself and test on multiple nodes. Still, worth at least starting the CI tests to see what turns up.

**Comment by ggouaillardet** [comment]
@rhc54 I pushed a few commits to get things working. for some reasons, the tests crash with gcc 6 but not with other compilers (!)

Feel free to squash all my commits.

When starting integrating this into Open MPI, we will need some extra configury logic in order to support the embedded `libevent` and/or `PMIx`.

**Comment by rhc54** [comment]
Wow - thanks @ggouaillardet ! I really appreciate the assist. We'll need to remove that "setup_debugger_flags" (and anything that uses the results) as PRRTE won't support MPIR (I have already removed it). We also need the wrapper not to link the results against libprrte as applications must never call ```prrte_init``` - all interactions between apps and PRRTE must solely be via PMIx.

**Comment by rhc54** [comment]
@ggouaillardet (or anyone else, for that matter) - can you please test this across multiple nodes? I think it is ready to go but am not currently setup for a multi-node test (working to set up now).

**Comment by rhc54** [comment]
I was able to make this run on a multi-node setup, but prte crashes when terminating. Haven't had a chance to dig into it but suspect a simple ordering issue on the shutdown procedure.

**Comment by ggouaillardet** [comment]
From `config/prrte_configure_options.m4`

```
AC_ARG_ENABLE([prrterun-prefix-by-default],
    [AC_HELP_STRING([--enable-prrte-prefix-by-default],
        [Make "prrterun ..." behave exactly the same as "prrte --prefix \$prefix" (where \$prefix is the value given to --prefix in configure)])])
```

the help string (prrte) does not match the configury option (prrterun).
which one should it be?

**Comment by rhc54** [comment]
Fixed - see what you think.

**Comment by jjhursey** [comment]
Ref OMPI PR towards this goal
 * https://github.com/open-mpi/ompi/pull/7202

**Comment by ggouaillardet** [comment]
In the mean time, I came up with a different way of handling the embedded PMIx
(long story short, do not test `libpmix.*`, use `libpmix.la` from the build dir, and take a bit of extra steps to correctly handle VPATH)

feel free to take some bits or simply drop it.
 
the inline diff below is on top of fc0b9e2b0693139a95c830d2ee1512cd321770fa

```diff
diff --git a/config/prrte_check_pmi.m4 b/config/prrte_check_pmi.m4
index e6e9707..14ad125 100644
--- a/config/prrte_check_pmi.m4
+++ b/config/prrte_check_pmi.m4
@@ -32,6 +32,10 @@ AC_DEFUN([PRRTE_CHECK_PMIX],[
                 [AC_HELP_STRING([--with-pmix(=DIR)],
                                 [Where to find PMIx support, optionally adding DIR to the search path])])
 
+    AC_ARG_WITH([pmix-embedded],
+                [AC_HELP_STRING([--with-pmix-embedded(=DIR)],
+                                [Where to find the embedded PMIx, skip the PMIx library test too])])
+
     AC_ARG_WITH([pmix-libdir],
                 [AC_HELP_STRING([--with-pmix-libdir=DIR],
                                 [Look for libpmix in the given directory DIR, DIR/lib or DIR/lib64])])
@@ -47,14 +51,21 @@ AC_DEFUN([PRRTE_CHECK_PMIX],[
 
     prrte_external_have_pmix1=0
 
-    # check for external pmix lib */
-    AS_IF([test -z "$with_pmix"],
-          [pmix_ext_install_dir=/usr],
-          [pmix_ext_install_dir=$with_pmix])
+    AS_IF([test -n "$with_pmix_embedded"],
+          [pmix_library=$PRRTE_TOP_BUILDDIR/$with_pmix_embedded/src/libpmix.la
+           pmix_ext_install_dir=$PRRTE_TOP_SRCDIR/$with_pmix_embedded
+           pmix_ext_install_dir2=$PRRTE_TOP_BUILDDIR/$with_pmix_embedded],
+          [pmix_library=-lpmix
+           # check for external pmix lib */
+           AS_IF([test -z "$with_pmix"],
+                 [pmix_ext_install_dir=/usr],
+                 [pmix_ext_install_dir=$with_pmix])
+           pmix_ext_install_dir2=$pmix_ext_install_dir])
 
     # Make sure we have the headers and libs in the correct location
     PRRTE_CHECK_WITHDIR([pmix], [$pmix_ext_install_dir/include], [pmix.h])
 
+    AS_IF([test -z "$with_pmix_embedded"], [
     AS_IF([test -n "$with_pmix_libdir"],
           [AC_MSG_CHECKING([libpmix.* in $with_pmix_libdir])
            files=`ls $with_pmix_libdir/libpmix.* 2> /dev/null | wc -l`
@@ -90,6 +101,7 @@ AC_DEFUN([PRRTE_CHECK_PMIX],[
                    pmix_ext_install_libdir=$pmix_ext_install_dir/lib],
                   [AC_MSG_RESULT([not found])
                    AC_MSG_ERROR([Cannot continue])])])])
+    ])
 
     # check the version
     prrte_external_pmix_save_CPPFLAGS=$CPPFLAGS
@@ -99,8 +111,11 @@ AC_DEFUN([PRRTE_CHECK_PMIX],[
     # if the pmix_version.h file does not exist, then
     # this must be from a pre-1.1.5 version
     AC_MSG_CHECKING([for PMIx version file])
-    CPPFLAGS="-I$pmix_ext_install_dir/include $CPPFLAGS"
-    AS_IF([test "x`ls $pmix_ext_install_dir/include/pmix_version.h 2> /dev/null`" = "x"],
+    CPPFLAGS="-I$pmix_ext_install_dir2/include $CPPFLAGS"
+    AS_IF([test -n "$with_pmix_embedded"],
+          [AS_IF([test "$PRRTE_TOP_SRCDIR" != "$PRRTE_TOP_BUILDDIR"],
+                 [CPPFLAGS="-I$PRRTE_TOP_BUILDDIR/$with_pmix_embedded $CPPFLAGS"])])
+    AS_IF([test "x`ls $pmix_ext_install_dir2/include/pmix_version.h 2> /dev/null`" = "x"],
            [AC_MSG_RESULT([not found - assuming pre-v2.0])
             AC_MSG_WARN([PRTE does not support PMIx versions])
             AC_MSG_WARN([less than v2.0 as only PMIx-based tools can])
@@ -166,20 +181,25 @@ AC_DEFUN([PRRTE_CHECK_PMIX],[
     LDFLAGS=$prrte_external_pmix_save_LDFLAGS
     LIBS=$prrte_external_pmix_save_LIBS
 
-    AS_IF([test "$pmix_ext_install_dir" != "/usr"],
-          [CPPFLAGS="-I$pmix_ext_install_dir/include $CPPFLAGS"
-           LDFLAGS="-L$pmix_ext_install_libdir $LDFLAGS"])
+    AS_IF([test -n "$with_pmix_embedded"],
+          [AS_IF([test "$PRRTE_TOP_SRCDIR" != "$PRRTE_TOP_BUILDDIR"],
+                 [CPPFLAGS="-I$pmix_ext_install_dir2/include -I$pmix_ext_install_dir/include $CPPFLAGS"],
+                 [CPPFLAGS="-I$pmix_ext_install_dir/include $CPPFLAGS"])],
+          [AS_IF([test "$pmix_ext_install_dir" != "/usr"],
+                 [CPPFLAGS="-I$pmix_ext_install_dir/include $CPPFLAGS"
+                  LDFLAGS="-L$pmix_ext_install_libdir $LDFLAGS"])])
 
-    CPPFLAGS="$CPPFLAGS -I$pmix_ext_install_dir/include"
     PRRTE_WRAPPER_FLAGS_ADD([CPPFLAGS], [-I$pmix_ext_install_dir/include])
 
     AS_IF([test "$enable_pmix_devel_support" = "yes"],
           [PRRTE_WRAPPER_FLAGS_ADD([CPPFLAGS], [-I$pmix_ext_install_dir/include/pmix -I$pmix_ext_install_dir/include/pmix/src -I$pmix_ext_install_dir/include/pmix/src/include])])
 
-    LDFLAGS="$LDFLAGS -L$pmix_ext_install_libdir"
-    PRRTE_WRAPPER_FLAGS_ADD([LDFLAGS], [-L$pmix_ext_install_libdir])
-    PRRTE_WRAPPER_FLAGS_ADD(LIBS, -lpmix)
+    AS_IF([test -z "$with_pmix_embedded"],
+          [LDFLAGS="$LDFLAGS -L$pmix_ext_install_libdir"
+           PRRTE_WRAPPER_FLAGS_ADD([LDFLAGS], [-L$pmix_ext_install_libdir])
+           PRRTE_WRAPPER_FLAGS_ADD(LIBS, -lpmix)])
 
+    AC_SUBST(pmix_library)
     prrte_external_pmix_happy=yes
 
     PRRTE_SUMMARY_ADD([[Required Packages]],[[PMIx]],[pmix],[yes ($pmix_ext_install_dir)])
diff --git a/src/Makefile.am b/src/Makefile.am
index beecdfe..94f7c34 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -49,7 +49,7 @@ libprrte_la_LIBADD = \
                util/libprrteutil.la \
                $(MCA_prrte_FRAMEWORK_LIBS)
 libprrte_la_DEPENDENCIES = $(libprrte_la_LIBADD)
-libprrte_la_LDFLAGS = -version-info $(libprrte_so_version) -lpmix
+libprrte_la_LDFLAGS = -version-info $(libprrte_so_version) $(pmix_library)
 
 # included subdirectory Makefile.am's and appended-to variables
 headers =
diff --git a/src/tools/prun/Makefile.am b/src/tools/prun/Makefile.am
index d733475..8dfe6d7 100644
--- a/src/tools/prun/Makefile.am
+++ b/src/tools/prun/Makefile.am
@@ -50,7 +50,7 @@ prun_LDADD = \
        $(top_builddir)/src/libprrte.la
 
 prun_LDFLAGS = \
-        -lpmix
+        $(pmix_library)
 
 distclean-local:
        rm -f $(man_pages)
```

and the diff below is for Open MPI
```diff
diff --git a/config/ompi_setup_prrte.m4 b/config/ompi_setup_prrte.m4
index 5082e3f..b7ebe4d 100644
--- a/config/ompi_setup_prrte.m4
+++ b/config/ompi_setup_prrte.m4
@@ -43,18 +43,17 @@ AC_DEFUN([OMPI_SETUP_PRRTE],[
         AS_IF([test -z $with_hwloc || test "$with_hwloc" = "internal" || test "$with_hwloc" = "yes"],
               [AC_MSG_WARN([INTERNAL HWLOC NOT CURRENTLY SUPPORTED FOR PRRTE])
                AC_MSG_ERROR([Cannot continue])])
-        AS_IF([test -z $with_pmix || test "$with_pmix" = "internal" || test "$with_pmix" = "yes"],
-              [AC_MSG_WARN([INTERNAL PMIx NOT CURRENTLY SUPPORTED FOR PRRTE])
-               AC_MSG_ERROR([Cannot continue])])
         AS_IF([test "$with_libevent" = "external"],
               [opal_prrte_libevent_arg=],
               [opal_prrte_libevent_arg="--with-libevent=$with_libevent"])
         AS_IF([test "$with_hwloc" = "external"],
               [opal_prrte_hwloc_arg=],
               [opal_prrte_hwloc_arg="--with-hwloc=$with_hwloc"])
-        AS_IF([test "$with_pmix" = "external"],
-              [opal_prrte_pmix_arg=],
-              [opal_prrte_pmix_arg="--with-pmix=$with_pmix"])
+        AS_IF([test -z "$with_pmix" || test "$with_pmix" = "internal"],
+              [opal_prrte_pmix_arg="--with-pmix-embedded=../opal/mca/pmix/pmix4x/openpmix $opal_prrte_args"],
+              [AS_IF([test "$with_pmix" = "external"],
+                     [opal_prrte_pmix_arg=],
+                     [opal_prrte_pmix_arg="--with-pmix=$with_pmix"])])
 
         opal_prrte_args="--prefix=$prefix $opal_prrte_libevent_arg $opal_prrte_hwloc_arg $opal_prrte_pmix_arg"
         AS_IF([test "$enable_debug" = "yes"],
```

**Comment by ggouaillardet** [comment]
@rhc54 I pushed some more commits to fix/cleanup misc stuff.
feel free to squash all of them.

**Comment by rhc54** [comment]
Thanks! Just FYI: the branch is likely going to be broken now and then as I "checkpoint" to move between the desktop and laptop. I have to rename all the mca/base code to avoid conflicts when we reference OMPI headers inside PRRTE (for the case of embedded libevent/hwloc/pmix).

**Comment by ggouaillardet** [comment]
@rhc54 how do you plan to have `prted` use the embedded PMIx ?
one option is to link (static) `opal/mca/pmix/pmix4x/openpmix/src/libpmix.la`, and an other option is to link dynamic/static `libopen-pal.so`.
In the first case, the binaries will be bigger, but you do not have to worry about conflicts.
In the second case, the binaries will be smaller, but there are likely conflicts to be taken care of.

I initially thought about the former, but if I read correctly between the lines, you might have chosen the latter.

**Comment by rhc54** [comment]
I was planning to link against libopen-pal as the hwloc, libevent, and pmix support is all statically pulled into there regardless of internal or external. Technically, it doesn't matter as apps won't link against prrte, but it just seemed easier for configure. Make sense?

Aso, I think this should now build cleanly against OMPI, though I won't try until the morning. Can you check and see if this actually works multi-node? I got it to compile, but then shut down for the night.

**Comment by rhc54** [comment]
Once this passes CI, I'm going to commit it so we can get the corresponding OMPI PR a chance to work - too many moving pieces.

**Pull request merged**
