### PR TITLE
Proposal: remove pcc

### PR DESCRIPTION
**Pull request by jsquyres**
The `pcc` wrapper compiler seems to be just a stand-in for the PMIx wrapper compiler -- it's effectively duplicate code.

Unless there's a reason to keep it, I propose to remove `pcc` and advise users to use the actual `pmixcc` wrapper compiler when they want to compile PMIx applications.

### CODE REVIEW

**Comment by jsquyres** [comment]
This is obviously up for discussion / debate (e.g., it is already known that the IBM CI will fail, because it's actively invoking `pcc`).  I just posted this PR to start the discussion.

**Comment by rhc54** [comment]
I have mixed feelings here, but am leaning to leaving `pcc`. The key thing is that it ensures the application is being built against the _same_ PMIx used by PRRTE, and thus it is guaranteed to be compatible.

On the other hand, the PMIx community guarantees backward compatibility between clients and servers (with some exceptions). Given that PRRTE only supports PMIx v3.1.5 or greater, that means any PMIx client library the user builds against _should_ work.

Given that PRRTE does not contain an embedded version of PMIx, and thus you _have to_ install PMIx separately anyway, and that PMIx tools such as `pattrs`, `pevent`, and `pquery` are of increasing value to users (thereby motivating the installation of PMIx tools along with the library), it probably isn't necessary to have a PRRTE wrapper compiler.

So I guess I can go either way... 🤷‍♂️

**Comment by jsquyres** [comment]
Fair 'nuff.  Let's see what others think...

**Comment by jjhursey** [comment]
I didn't know there was a `pmixcc` - I guess I never noticed. IBM CI was using `pcc` to pick up the hwloc and libevent. We could probably move to using `pmixcc` without much problem.

It is kind of strange for a runtime (e.g., PRRTE, SLURM, JSM) to provide a wrapper compiler, but it does make sense for a programming library (e.g., OMPI, PMIx) to have one to pull in the 'right' dependencies.

So I'm leaning towards keeping the wrapper compiler in OpenPMIx, and removing it from PRRTE.

**Comment by jjhursey** [comment]
Fix for IBM CI (PRRTE test suite) - try to use `pmixcc` instead of `pcc`, when available
 * https://github.com/openpmix/pmix-tests/pull/63

Note that OpenPMIx `master` has a `pmixcc`, but the latest OpenPMIx release (3.1.5) does not have a wrapper compiler. It was added in PR https://github.com/openpmix/openpmix/pull/1460

So if you are building a PMIx 3.x app you need to manually add -lpmix and friends. Not too bad, but I don't know if that changes things WRT keeping `pcc`.

**Comment by jjhursey** [comment]
Fixed the `pmixcc` issue - IBM CI should pass now.
bot:ibm:retest

**Comment by jjhursey** [comment]
Per developer teleconf on May 14, 2020
 * Noted that PMIx 3.1.5 (and 3.1.x series) does not have the `pmixcc` wrapper compiler. Only `master` (a.k.a. `v4`) has the `pmixcc` wrapper compiler.
 * Feeling was that we need `pcc` to stay around for configurations running 3.1.x, at least for a little while.
 * Suggested that we suggest folks move from `pcc` to `pmixcc` in PRRTE v2, then deprecate in v3, and remove in v4. Can we throw a warning in `pcc` if we know they are compiling against PMIx v4.x or later?

**Comment by jjhursey** [comment]
Notes from March 25, 2021 Teleconf:
 * We will make a final decision on this PR before we roll a release for PRTE v2.0.0
 * Summary:
   * `pmixcc` is provided by OpenPMIx v4.0.0 and later (not in the v3.x series)
   * PRRTE already requires at least OpenPMIx v4.0.1 - See PR #848 
   * `pcc` is provided by PRRTE, but PRRTE does not have a library to link against. It is duplicate code with `pmixcc`
 * My personal leaning is to remove it from PRRTE. Those building PMIx applications should use the wrapper compiler from their PMIx implementation.

**Comment by jjhursey** [comment]
In preparation for our discussion on this PR this week, I went ahead and rebased it on master. So it is ready to go if we decide to remove `pcc`.

**Comment by jjhursey** [comment]
Per teleconf April 8, 2021,
 * Decided that the `pcc` compiler both duplicates functionality from `pmixcc` (which will already be present on the system), and is confusing to users. So we will commit this PR to remove the tool.
 * Sorry for the delay on acting on this PR. Thanks for filing! I'll cherry-pick it over to the v2.0 branch

**Review by jjhursey — APPROVED** [review]

**Comment by rhc54** [comment]
I really, REALLY wish you hadn't done this as it breaks the build of all the examples and tests in PRRTE. People don't include the PMIx install in there PATH as there is no need to do so - now, they have to figure out which PMIx PRRTE was built against, find that installation, and then add it to the PATH just to build the examples or tests.

The rationale for removing this doesn't come close to compensating for the pain we just created.

**Pull request merged**
